"""ingestion: add flashcard/note/revision-sheet counters

Revision ID: 08d410cf79e9
Revises: b7d07ac8deec
Create Date: 2026-08-02 11:20:57.892680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d410cf79e9'
down_revision = 'b7d07ac8deec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('flashcards_generated', sa.Integer(), nullable=False), schema='ingestion')
    op.add_column('ingestion_jobs', sa.Column('notes_generated', sa.Integer(), nullable=False), schema='ingestion')
    op.add_column('ingestion_jobs', sa.Column('revision_sheets_generated', sa.Integer(), nullable=False), schema='ingestion')
    # NOTE: autogenerate wanted to drop ix_ingestion_jobs_checksum/_status here —
    # they're real, intentional indexes from b7d07ac8deec that just weren't
    # declared via index=True on the model columns. Keeping them; see the
    # matching index=True fix on IngestionJob.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'revision_sheets_generated', schema='ingestion')
    op.drop_column('ingestion_jobs', 'notes_generated', schema='ingestion')
    op.drop_column('ingestion_jobs', 'flashcards_generated', schema='ingestion')
    # ### end Alembic commands ###
