"""learning module: concept_mastery

Revision ID: 38e32c83fa42
Revises: d20b9a32f6bc
Create Date: 2026-08-01 17:57:26.522979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e32c83fa42'
down_revision = 'd20b9a32f6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 'learning' wasn't in the original ADR-0001 schema list — create it here.
    op.execute("CREATE SCHEMA IF NOT EXISTS learning")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.String(length=20), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['academic.concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_concept_mastery_user_concept'),
    schema='learning'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_mastery', schema='learning')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS learning CASCADE")
