"""assessment module: assessments, assessment_questions, attempts, attempt_answers

Revision ID: 513e0d9ed760
Revises: 961ed6ca880b
Create Date: 2026-08-01 17:09:37.910179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513e0d9ed760'
down_revision = '961ed6ca880b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('marks_per_question', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('negative_marks_per_question', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='assessment'
    )
    op.create_table('attempts',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='assessment'
    )
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['cms.content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='assessment'
    )
    op.create_table('attempt_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment.attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['cms.content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='assessment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt_answers', schema='assessment')
    op.drop_table('assessment_questions', schema='assessment')
    op.drop_table('attempts', schema='assessment')
    op.drop_table('assessments', schema='assessment')
    # ### end Alembic commands ###
