"""add next_review_at to concept_mastery

Revision ID: 6fa4de3d4b47
Revises: 38e32c83fa42
Create Date: 2026-08-01 18:06:31.533699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa4de3d4b47'
down_revision = '38e32c83fa42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_mastery', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True), schema='learning')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_mastery', 'next_review_at', schema='learning')
    # ### end Alembic commands ###
