"""micro-competency layer: academic.micro_competencies + content_items link

Revision ID: 75b3a8b9b245
Revises: b6accd4cd83f
Create Date: 2026-08-01 23:17:45.775668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b3a8b9b245'
down_revision = 'b6accd4cd83f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_competencies',
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['academic.concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='academic'
    )
    op.add_column('content_items', sa.Column('micro_competency_id', sa.UUID(), nullable=True), schema='cms')
    op.create_foreign_key(None, 'content_items', 'micro_competencies', ['micro_competency_id'], ['id'], source_schema='cms', referent_schema='academic', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_items', schema='cms', type_='foreignkey')
    op.drop_column('content_items', 'micro_competency_id', schema='cms')
    op.drop_table('micro_competencies', schema='academic')
    # ### end Alembic commands ###
