"""knowledge module: knowledge_units foundation

Revision ID: 811cc52b1937
Revises: 08d410cf79e9
Create Date: 2026-08-02 13:59:34.837042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811cc52b1937'
down_revision = '08d410cf79e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 'knowledge' wasn't in the original ADR-0001 schema list — create it
    # here (same pattern as 'learning' in 38e32c83fa42, 'ingestion' in
    # b7d07ac8deec).
    op.execute("CREATE SCHEMA IF NOT EXISTS knowledge")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_units',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('structured_facts', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_section_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_detail', sa.Text(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['academic.concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_section_id'], ['ingestion.ingestion_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['knowledge.knowledge_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index('ix_knowledge_units_concept', 'knowledge_units', ['concept_id'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_units_content_hash', 'knowledge_units', ['content_hash'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_units_content_hash', table_name='knowledge_units', schema='knowledge')
    op.drop_index('ix_knowledge_units_concept', table_name='knowledge_units', schema='knowledge')
    op.drop_table('knowledge_units', schema='knowledge')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS knowledge CASCADE")
