"""ingestion: add knowledge_units_created/rejected counters

Revision ID: 823b50e0e64f
Revises: 811cc52b1937
Create Date: 2026-08-02 14:03:46.298572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823b50e0e64f'
down_revision = '811cc52b1937'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('knowledge_units_created', sa.Integer(), nullable=False), schema='ingestion')
    op.add_column('ingestion_jobs', sa.Column('knowledge_units_rejected', sa.Integer(), nullable=False), schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'knowledge_units_rejected', schema='ingestion')
    op.drop_column('ingestion_jobs', 'knowledge_units_created', schema='ingestion')
    # ### end Alembic commands ###
