"""cms module: content_items, content_versions, content_reviews

Revision ID: 961ed6ca880b
Revises: a7d0fe8eb174
Create Date: 2026-08-01 15:56:03.326832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '961ed6ca880b'
down_revision = 'a7d0fe8eb174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('latest_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['academic.concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_version_id'], ['cms.content_versions.id'], name='fk_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['latest_version_id'], ['cms.content_versions.id'], name='fk_latest_version', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_state', sa.String(length=30), nullable=False),
    sa.Column('ai_check_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('authored_by', sa.UUID(), nullable=True),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['cms.content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_table('content_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['cms.content_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    # `use_alter=True` FKs on content_items (circular ref to
    # content_versions, which doesn't exist yet when content_items is
    # created) are dropped silently by op.create_table() rather than
    # deferred automatically — they need to be added explicitly here.
    op.create_foreign_key(
        'fk_current_version', 'content_items', 'content_versions',
        ['current_version_id'], ['id'], source_schema='cms', referent_schema='cms',
    )
    op.create_foreign_key(
        'fk_latest_version', 'content_items', 'content_versions',
        ['latest_version_id'], ['id'], source_schema='cms', referent_schema='cms',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_latest_version', 'content_items', schema='cms', type_='foreignkey')
    op.drop_constraint('fk_current_version', 'content_items', schema='cms', type_='foreignkey')
    op.drop_table('content_reviews', schema='cms')
    op.drop_table('content_versions', schema='cms')
    op.drop_table('content_items', schema='cms')
    # ### end Alembic commands ###
