"""learning: micro_competency_mastery

Revision ID: 975d1f4038f3
Revises: 75b3a8b9b245
Create Date: 2026-08-01 23:22:37.370854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975d1f4038f3'
down_revision = '75b3a8b9b245'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_competency_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('micro_competency_id', sa.UUID(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.String(length=20), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['micro_competency_id'], ['academic.micro_competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'micro_competency_id', name='uq_micro_competency_mastery_user_mc'),
    schema='learning'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('micro_competency_mastery', schema='learning')
    # ### end Alembic commands ###
