"""ingestion module: ingestion_jobs, ingestion_sections

Revision ID: b7d07ac8deec
Revises: 975d1f4038f3
Create Date: 2026-08-02 10:54:57.104300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d07ac8deec'
down_revision = '975d1f4038f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 'ingestion' wasn't in the original ADR-0001 schema list — create it here
    # (same pattern as 'learning' in 38e32c83fa42).
    op.execute("CREATE SCHEMA IF NOT EXISTS ingestion")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('source_file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_checksum', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage_detail', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sections_detected', sa.Integer(), nullable=False),
    sa.Column('questions_generated', sa.Integer(), nullable=False),
    sa.Column('questions_deduped', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['academic.chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['academic.subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_index('ix_ingestion_jobs_checksum', 'ingestion_jobs', ['file_checksum'], schema='ingestion')
    op.create_index('ix_ingestion_jobs_status', 'ingestion_jobs', ['status'], schema='ingestion')
    op.create_table('ingestion_sections',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('matched_concept_id', sa.UUID(), nullable=True),
    sa.Column('questions_generated', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion.ingestion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_concept_id'], ['academic.concepts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_sections', schema='ingestion')
    op.drop_index('ix_ingestion_jobs_status', table_name='ingestion_jobs', schema='ingestion')
    op.drop_index('ix_ingestion_jobs_checksum', table_name='ingestion_jobs', schema='ingestion')
    op.drop_table('ingestion_jobs', schema='ingestion')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS ingestion CASCADE")
