"""CF-SOURCE-001 — read-only inventory scan of the configured NCERT Books root.

Usage (from apps/backend):

    python -m scripts.ncert_books_inventory_report

Writes:
    docs/audits/ncert_books_inventory_<date>.json
    docs/audits/ncert_books_inventory_<date>.md

No AI calls. No DB writes. Does not generate MCQs.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BACKEND = Path(__file__).resolve().parents[1]
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.modules.ingestion.services.ncert_books_inventory import (  # noqa: E402
    scan_ncert_books,
    write_inventory_report,
)
from app.modules.ingestion.services.ncert_canonical_source import get_ncert_source_root  # noqa: E402


def _md_report(payload: dict) -> str:
    lines = [
        "# NCERT Books inventory (CF-SOURCE-001)",
        "",
        f"- Root: `{payload['root']}`",
        f"- Total PDFs: **{payload['total_pdfs']}**",
        f"- Readable: **{payload['readable']}**",
        f"- Duplicates: **{payload['duplicates']}**",
        f"- Ambiguous: **{payload['ambiguous']}**",
        f"- Unreadable: **{payload['unreadable']}**",
        f"- Unexpected structure: **{payload['unexpected']}**",
        "",
        "## Matrix",
        "",
    ]
    for key, bucket in payload["matrix"].items():
        lines.append(f"### {key}")
        lines.append("")
        lines.append(
            f"PDFs={bucket['total_pdfs']} · chapters={bucket['chapters']} · "
            f"readable_chapters={bucket['readable_chapters']} · "
            f"duplicates={bucket['duplicates']} · ambiguous={bucket['ambiguous']} · "
            f"supplemental={bucket['supplemental']}"
        )
        lines.append("")
        lines.append("| Ch | Title | File | Relative | Readable | Status | Hash |")
        lines.append("|---:|---|---|---|:---:|---|---|")
        for e in bucket["entries"]:
            if e["kind"] != "chapter":
                continue
            title = (e.get("chapter_title") or "").replace("|", "/")
            sha = (e.get("checksum_sha256") or "")[:12]
            lines.append(
                f"| {e.get('chapter_number') or ''} | {title} | `{e['file_name']}` | "
                f"`{e['relative_path']}` | {e['readable']} | {e['status']} | `{sha}` |"
            )
        lines.append("")
    if payload.get("anomalies"):
        lines.append("## Anomalies")
        lines.append("")
        for a in payload["anomalies"][:200]:
            lines.append(f"- `{a.get('code')}`: {a.get('message')} ({a.get('relative_path') or a.get('path') or ''})")
        lines.append("")
    lines.append(
        "_Generated by CF-SOURCE-001. Textbook PDFs are not committed to Git._"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    root = get_ncert_source_root()
    report = scan_ncert_books(root=root, compute_hashes=True)
    payload = report.to_dict()
    stamp = date.today().strftime("%Y%m%d")
    out_dir = ROOT / "docs" / "audits"
    json_path = out_dir / f"ncert_books_inventory_{stamp}.json"
    md_path = out_dir / f"ncert_books_inventory_{stamp}.md"
    write_inventory_report(report, json_path)
    md_path.write_text(_md_report(payload), encoding="utf-8")
    print(f"root={root}")
    print(f"total_pdfs={payload['total_pdfs']} readable={payload['readable']}")
    print(f"wrote {json_path}")
    print(f"wrote {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
