"""NCERT Biology flashcard seed — Botany + Zoology (Class 11–12) for SEED-V1.

concept_code values must match docs/acquisition/flashcards/SEED-V1/concept_map.json.
Chapter-level source_reference only — no page numbers.
"""

from __future__ import annotations

CARDS: list[dict] = [
    {
        'card_key': 'bio-lw-01',
        'concept_code': 'lw-diversity-what-is-living',
        'front': 'List key features used to define living organisms.',
        'back': 'Growth, reproduction, metabolism, cellular organisation, consciousness (response to stimuli).',
        'explanation': 'No single feature alone is absolute; metabolism and cellular organisation are defining.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-02',
        'concept_code': 'lw-taxonomy-systematics',
        'front': 'Differentiate taxonomy and systematics.',
        'back': 'Taxonomy: identification, nomenclature, classification; systematics also includes evolutionary relationships.',
        'explanation': 'Systematics is broader and phylogenetic in emphasis.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-03',
        'concept_code': 'lw-binomial-nomenclature',
        'front': 'State the rules of binomial nomenclature (Linnaeus).',
        'back': 'Each species has a two-part Latin name: Generic name + specific epithet; italicised/underlined; genus capitalised.',
        'explanation': 'Names are unique and universal.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-04',
        'concept_code': 'lw-biological-species-concept-mayr',
        'front': 'State Ernst Mayr’s biological species concept.',
        'back': 'Species are groups of actually or potentially interbreeding natural populations that are reproductively isolated from other such groups.',
        'explanation': 'Emphasises reproductive isolation.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-05',
        'concept_code': 'lw-taxonomic-categories-ranks',
        'front': 'List taxonomic categories from species to kingdom.',
        'back': 'Species → Genus → Family → Order → Class → Phylum/Division → Kingdom.',
        'explanation': 'Each rank is a taxon.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-06',
        'concept_code': 'lw-taxonomic-hierarchy-relations',
        'front': 'As one moves higher in the taxonomic hierarchy, what happens to shared characters?',
        'back': 'Number of common characters decreases; groups become more inclusive and diverse.',
        'explanation': 'Higher taxa are more heterogeneous.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-07',
        'concept_code': 'lw-nomenclature-identification-codes',
        'front': 'Name the codes that govern scientific naming of organisms.',
        'back': 'ICBN/ICN (plants), ICZN (animals), and related international codes for other groups.',
        'explanation': 'Ensure uniqueness and stability of names.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-lw-08',
        'concept_code': 'sv2c-botany-02',
        'front': 'What is a herbarium? Name one use of botanical gardens.',
        'back': 'Herbarium: storehouse of dried, pressed, labelled plant specimens. Botanical gardens: living plant collections for study/conservation.',
        'explanation': 'Taxonomic aids also include museums, keys, and monographs.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — The Living World',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-01',
        'concept_code': 'bc-classification-history',
        'front': 'Limitation of the two-kingdom classification?',
        'back': 'It did not distinguish prokaryotes/eukaryotes, unicellular/multicellular, or photosynthetic/non-photosynthetic clearly.',
        'explanation': 'Aristotle used simple traits; Linnaeus had Plantae and Animalia.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-02',
        'concept_code': 'bc-whittaker-five-kingdom',
        'front': 'Name Whittaker’s five kingdoms and main criteria.',
        'back': 'Monera, Protista, Fungi, Plantae, Animalia — based on cell structure, body organisation, mode of nutrition, reproduction, phylogenetic relationships.',
        'explanation': 'Proposed in 1969.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-03',
        'concept_code': 'bc-monera-bacteria-general',
        'front': 'Give bacterial shapes recognised in NCERT.',
        'back': 'Coccus (spherical), bacillus (rod), vibrium (comma), spirillum (spiral).',
        'explanation': 'Bacteria are the most abundant microorganisms.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-04',
        'concept_code': 'bc-archaebacteria',
        'front': 'Name three groups of archaebacteria and their habitats.',
        'back': 'Halophiles (salty), thermoacidophiles (hot acidic), methanogens (marshy/gut — produce methane).',
        'explanation': 'Archaebacteria have distinct cell wall chemistry.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-05',
        'concept_code': 'bc-eubacteria-mycoplasma',
        'front': 'What are cyanobacteria? What is unique about Mycoplasma?',
        'back': 'Cyanobacteria: photosynthetic prokaryotes (blue-green algae). Mycoplasma: smallest living cells; lack cell wall.',
        'explanation': 'Heterotrophic bacteria include decomposers and pathogens.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-06',
        'concept_code': 'bc-protista-overview-groups',
        'front': 'List major Protista groups in NCERT.',
        'back': 'Chrysophytes, Dinoflagellates, Euglenoids, Slime moulds, Protozoans.',
        'explanation': 'Mostly unicellular eukaryotes; aquatic habitats common.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-07',
        'concept_code': 'bc-fungi-structure-nutrition-repro',
        'front': 'Describe fungal nutrition and body organisation.',
        'back': 'Heterotrophic (saprophytic/parasitic/symbiotic); body of hyphae forming mycelium; cell wall of chitin.',
        'explanation': 'Reproduce by vegetative, asexual and sexual means; classes include Phycomycetes, Ascomycetes, Basidiomycetes, Deuteromycetes.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-08',
        'concept_code': 'bc-viruses-viroids-prions-lichens',
        'front': 'Differentiate virus, viroid and prion briefly.',
        'back': 'Virus: nucleic acid + protein coat; viroid: free RNA, no protein coat; prion: infectious protein particles.',
        'explanation': 'Lichens: symbiotic association of algae/cyanobacteria and fungi.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-09',
        'concept_code': 'bc-plantae-animalia-salient',
        'front': 'Salient feature separating Plantae and Animalia in five-kingdom overview?',
        'back': 'Plantae: multicellular eukaryotes with cellulose wall, mostly autotrophic; Animalia: multicellular eukaryotes without cell wall, heterotrophic, usually ingestive.',
        'explanation': 'Detailed treatment follows in Plant Kingdom / Animal Kingdom chapters.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-10',
        'concept_code': 'bc-whittaker-five-kingdom',
        'front': 'Why were fungi placed in a separate kingdom?',
        'back': 'Distinct cell wall (chitin), absorptive heterotrophic nutrition, and unique organisation vs plants and animals.',
        'explanation': 'Whittaker criteria emphasise mode of nutrition.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-11',
        'concept_code': 'bc-eubacteria-mycoplasma',
        'front': 'Role of chemosynthetic bacteria?',
        'back': 'Oxidise inorganic substances (e.g. nitrifying bacteria) to obtain energy; important in nutrient cycling.',
        'explanation': 'Autotrophic without photosynthesis.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-bc-12',
        'concept_code': 'bc-viruses-viroids-prions-lichens',
        'front': 'Why are viruses not included in Whittaker’s five kingdoms?',
        'back': 'They are acellular and inert outside host cells; not truly ‘living’ in the cellular sense.',
        'explanation': 'Obligate parasites requiring host machinery.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biological Classification',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-01',
        'concept_code': 'pk-algae-general-characters-and-forms',
        'front': 'Give general characters of algae.',
        'back': 'Chlorophyll-bearing, simple thalloid, largely aquatic; unicellular to colonial to filamentous forms.',
        'explanation': 'Cell wall usually cellulose; reproduce vegetatively, asexually and sexually.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-02',
        'concept_code': 'pk-chlorophyceae',
        'front': 'Pigments and stored food in Chlorophyceae?',
        'back': 'Chlorophyll a and b; store starch; cell wall cellulose.',
        'explanation': 'Examples: Chlamydomonas, Volvox, Spirogyra, Ulothrix.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-03',
        'concept_code': 'pk-phaeophyceae',
        'front': 'Distinctive features of Phaeophyceae (brown algae)?',
        'back': 'Chlorophyll a, c, carotenoids, fucoxanthin; store laminarin/mannitol; algin in cell wall.',
        'explanation': 'Mostly marine; e.g. Laminaria, Fucus, Sargassum.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-04',
        'concept_code': 'pk-rhodophyceae',
        'front': 'Why are Rhodophyceae red?',
        'back': 'Dominance of r-phycoerythrin; also chlorophyll a, d; store floridean starch.',
        'explanation': 'Occur in well-lighted regions to great depths.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-05',
        'concept_code': 'pk-algae-reproduction',
        'front': 'Distinguish isogamy, anisogamy and oogamy in algae.',
        'back': 'Isogamy: similar gametes; anisogamy: dissimilar gametes; oogamy: large non-motile egg + small motile sperm.',
        'explanation': 'Vegetative fragmentation and zoospores also common.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-06',
        'concept_code': 'pk-algae-economic-importance',
        'front': 'Name two economic uses of algae.',
        'back': 'Agar (Gelidium/Gracilaria); algin (brown algae); carrageenan; food (Porphyra, Laminaria); CO₂ fixation / O₂ release.',
        'explanation': 'Also used as hydrocolloids and soil binders in some contexts.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-07',
        'concept_code': 'pk-bryophytes-general-features',
        'front': 'Why are bryophytes called amphibians of the plant kingdom?',
        'back': 'They live in soil but need water for sexual reproduction (motile antherozoids).',
        'explanation': 'Lack true roots, stems, leaves; thallus or leafy gametophyte dominant.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-08',
        'concept_code': 'pk-bryophyte-reproduction-and-sporophyte',
        'front': 'Describe the bryophyte sporophyte’s dependence.',
        'back': 'Sporophyte is multicellular but attached to and nutritionally dependent on the gametophyte.',
        'explanation': 'Produces haploid spores by meiosis.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-09',
        'concept_code': 'pk-liverworts',
        'front': 'Key feature of liverworts?',
        'back': 'Thalloid gametophyte (dorsiventral); asexual gemmae cups common; e.g. Marchantia.',
        'explanation': 'Sporophyte has foot, seta, capsule.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-10',
        'concept_code': 'pk-mosses',
        'front': 'Stages in moss gametophyte development?',
        'back': 'Protonema (creeping, green, branched) → leafy gametophore bearing sex organs.',
        'explanation': 'Examples: Funaria, Polytrichum, Sphagnum.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-11',
        'concept_code': 'pk-pteridophytes-vascular-organisation',
        'front': 'What first appears in pteridophytes among land plants?',
        'back': 'True vascular tissues (xylem and phloem) and independent sporophyte with roots, stem, leaves.',
        'explanation': 'Still need water for fertilisation.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-12',
        'concept_code': 'pk-pteridophyte-life-cycle-and-prothallus',
        'front': 'What is a prothallus?',
        'back': 'Independent, photosynthetic, haploid gametophyte of pteridophytes; bears antheridia and archegonia.',
        'explanation': 'Usually short-lived and inconspicuous.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-13',
        'concept_code': 'pk-heterospory-and-seed-habit-precursor',
        'front': 'What is heterospory and why is it important?',
        'back': 'Production of two spore types (micro- and megaspores); precursor to the seed habit.',
        'explanation': 'Seen in Selaginella, Salvinia, etc.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-14',
        'concept_code': 'pk-gymnosperms-characters-and-reproduction',
        'front': 'Meaning of ‘gymnosperm’ and key reproductive feature?',
        'back': '‘Naked seeds’ — ovules not enclosed by ovary; seeds exposed on megasporophylls.',
        'explanation': 'Heterosporous; pollen tubes carry male gametes; no need for external water for fertilisation.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-15',
        'concept_code': 'pk-angiosperms-flowers-fruits-and-classes',
        'front': 'Unique features of angiosperms?',
        'back': 'Flowers; seeds enclosed in fruits; double fertilisation; monocots and dicots.',
        'explanation': 'Most successful and diverse plant group.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pk-16',
        'concept_code': 'pk-artificial-natural-phylogenetic-systems',
        'front': 'Differentiate artificial, natural and phylogenetic classification.',
        'back': 'Artificial: few morphological traits; natural: many morphological characters; phylogenetic: evolutionary relationships.',
        'explanation': 'Modern taxonomy aims at phylogenetic systems.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'bio-cell-01',
        'concept_code': 'prokaryote-eukaryote',
        'front': 'Key differences between prokaryotic and eukaryotic cells?',
        'back': 'Prokaryotes: no membrane-bound nucleus/organelles, 70S ribosomes; eukaryotes: true nucleus, membrane organelles, 80S ribosomes.',
        'explanation': 'Prokaryotes include bacteria and blue-green algae.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Cell: The Unit of Life',
        'class_level': '11',
    },
    {
        'card_key': 'bio-cell-02',
        'concept_code': 'fluid-mosaic',
        'front': 'State the fluid mosaic model (Singer and Nicolson).',
        'back': 'Plasma membrane is a quasi-fluid phospholipid bilayer with proteins floating like a mosaic.',
        'explanation': 'Explains fluidity and selective permeability.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Cell: The Unit of Life',
        'class_level': '11',
    },
    {
        'card_key': 'bio-cell-03',
        'concept_code': 'mitochondria-chloroplast',
        'front': 'Shared features of mitochondria and chloroplasts?',
        'back': 'Double membrane; own circular DNA and 70S ribosomes; semi-autonomous; involved in energy conversion.',
        'explanation': 'Mitochondria: ATP via respiration; chloroplasts: photosynthesis.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Cell: The Unit of Life',
        'class_level': '11',
    },
    {
        'card_key': 'bio-cell-04',
        'concept_code': 'mitochondria-chloroplast',
        'front': 'Where do Krebs cycle and light reactions occur?',
        'back': 'Krebs cycle: mitochondrial matrix; light reactions: thylakoid membranes of chloroplast.',
        'explanation': 'Oxidative phosphorylation on inner mitochondrial membrane.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Cell: The Unit of Life',
        'class_level': '11',
    },
    {
        'card_key': 'bio-cell-05',
        'concept_code': 'prokaryote-eukaryote',
        'front': 'Do prokaryotes have ribosomes? Which type?',
        'back': 'Yes — 70S ribosomes (50S + 30S subunits).',
        'explanation': 'Eukaryotic cytosol has 80S (60S + 40S).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Cell: The Unit of Life',
        'class_level': '11',
    },
    {
        'card_key': 'bio-cell-06',
        'concept_code': 'fluid-mosaic',
        'front': 'Role of cholesterol in the plasma membrane (qualitative)?',
        'back': 'Modulates fluidity; present in animal cell membranes.',
        'explanation': 'Membrane also contains glycolipids/glycoproteins important in recognition.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Cell: The Unit of Life',
        'class_level': '11',
    },
    {
        'card_key': 'bio-morph-01',
        'concept_code': 'sv2c-botany-05',
        'front': 'Give one modification each of root, stem and leaf.',
        'back': 'Root: storage (carrot) / prop (banyan); stem: tuber (potato) / tendril (grape); leaf: tendril (pea) / spine (cactus).',
        'explanation': 'Modifications serve storage, support, protection, photosynthesis, etc.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Morphology of Flowering Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-morph-02',
        'concept_code': 'sv2c-botany-05',
        'front': 'What are pneumatophores?',
        'back': 'Negatively geotropic roots of mangroves that grow upward for respiration.',
        'explanation': 'Adaptation to waterlogged, oxygen-poor soil.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Morphology of Flowering Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-morph-03',
        'concept_code': 'sv2c-botany-06',
        'front': 'What does a floral formula represent?',
        'back': 'Symbolic representation of flower parts: calyx, corolla, androecium, gynoecium, symmetry, sexuality, etc.',
        'explanation': 'Brackets and fusion symbols show cohesion/adhesion.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Morphology of Flowering Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-morph-04',
        'concept_code': 'sv2c-botany-06',
        'front': 'Name four types of placentation.',
        'back': 'Marginal, axile, parietal, free central (also basal, as in NCERT).',
        'explanation': 'Placentation = arrangement of ovules in the ovary.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Morphology of Flowering Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-morph-05',
        'concept_code': 'sv2c-botany-06',
        'front': 'Differentiate axile and parietal placentation.',
        'back': 'Axile: ovules on central axis with septa (multilocular); parietal: ovules on inner ovary wall (unilocular, often syncarpous).',
        'explanation': 'Tomato (axile); mustard (parietal) as typical examples.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Morphology of Flowering Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-01',
        'concept_code': 'photophosphorylation',
        'front': 'What is photophosphorylation?',
        'back': 'ATP synthesis driven by light-dependent electron transport in chloroplasts.',
        'explanation': 'Can be cyclic or non-cyclic.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-02',
        'concept_code': 'photophosphorylation',
        'front': 'Difference between cyclic and non-cyclic photophosphorylation?',
        'back': 'Non-cyclic: Z-scheme, both PSI & PSII, O₂ evolved, NADPH + ATP; cyclic: only PSI, ATP only, no O₂/NADPH.',
        'explanation': 'Electrons return to PSI in cyclic path.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-03',
        'concept_code': 'c3-c4-pathway',
        'front': 'Primary CO₂ acceptor in C₃ vs C₄ plants?',
        'back': 'C₃: RuBP (Rubisco) → 3-PGA; C₄: PEP (PEP carboxylase) → OAA (4-C).',
        'explanation': 'C₄ plants show Kranz anatomy.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-04',
        'concept_code': 'c3-c4-pathway',
        'front': 'Advantage of C₄ pathway?',
        'back': 'Minimises photorespiration; efficient CO₂ fixation at high light/temperature; concentrates CO₂ at Rubisco.',
        'explanation': 'Spatial separation: mesophyll and bundle sheath.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-05',
        'concept_code': 'photorespiration',
        'front': 'What is photorespiration?',
        'back': 'O₂ competes with CO₂ at Rubisco; RuBP oxygenase activity yields phosphoglycolate — wasteful pathway releasing CO₂ without ATP/NADPH gain.',
        'explanation': 'More significant in C₃ plants.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-06',
        'concept_code': 'limiting-factors',
        'front': 'State Blackman’s law of limiting factors.',
        'back': 'When a process depends on several factors, rate is limited by the factor nearest its minimum.',
        'explanation': 'Applies to light, CO₂, temperature in photosynthesis.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-07',
        'concept_code': 'limiting-factors',
        'front': 'At low light intensity, which factor usually limits photosynthesis?',
        'back': 'Light intensity (until another factor becomes limiting).',
        'explanation': 'CO₂ may limit at high light if concentration is low.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-ps-08',
        'concept_code': 'photorespiration',
        'front': 'Why do C₄ plants show little photorespiration?',
        'back': 'PEP carboxylase has high affinity for CO₂ and no oxygenase activity; bundle sheath CO₂ concentration is high.',
        'explanation': 'Rubisco operates under CO₂-rich conditions.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Photosynthesis in Higher Plants',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pgd-01',
        'concept_code': 'sv2c-botany-13',
        'front': 'Main physiological roles of auxin?',
        'back': 'Apical dominance, cell elongation, root initiation, fruit development; used in weedicides (2,4-D).',
        'explanation': 'Natural auxin: IAA.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Growth and Development',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pgd-02',
        'concept_code': 'sv2c-botany-13',
        'front': 'Roles of gibberellin and cytokinin?',
        'back': 'GA: stem elongation, bolting, seed germination, delaying senescence; CK: cell division, delay senescence, overcome apical dominance with auxin.',
        'explanation': 'Ethylene: fruit ripening, senescence; ABA: stress hormone, stomatal closure, dormancy.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Growth and Development',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pgd-03',
        'concept_code': 'sv2c-botany-13',
        'front': 'Which PGR promotes fruit ripening and which closes stomata in stress?',
        'back': 'Ethylene promotes ripening; abscisic acid (ABA) closes stomata under water stress.',
        'explanation': 'ABA is often antagonistic to growth promoters.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Growth and Development',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pgd-04',
        'concept_code': 'sv2c-botany-14',
        'front': 'Define photoperiodism; SDP vs LDP.',
        'back': 'Flowering response to relative day/night length. SDP: flower when day < critical; LDP: when day > critical.',
        'explanation': 'Night length is often the critical factor.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Growth and Development',
        'class_level': '11',
    },
    {
        'card_key': 'bio-pgd-05',
        'concept_code': 'sv2c-botany-14',
        'front': 'What is vernalisation?',
        'back': 'Promotion of flowering by a period of low temperature.',
        'explanation': 'Important in winter varieties of cereals and biennials.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Plant Growth and Development',
        'class_level': '11',
    },
    {
        'card_key': 'bio-srfp-01',
        'concept_code': 'sv2c-botany-15',
        'front': 'What is double fertilisation in angiosperms?',
        'back': 'One male gamete fuses with egg (syngamy → zygote); other fuses with two polar nuclei (triple fusion → PEN).',
        'explanation': 'Unique to angiosperms.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Sexual Reproduction in Flowering Plants',
        'class_level': '12',
    },
    {
        'card_key': 'bio-srfp-02',
        'concept_code': 'sv2c-botany-15',
        'front': 'Products of syngamy and triple fusion?',
        'back': 'Syngamy → diploid zygote; triple fusion → triploid primary endosperm nucleus (PEN).',
        'explanation': 'Endosperm nourishes the developing embryo.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Sexual Reproduction in Flowering Plants',
        'class_level': '12',
    },
    {
        'card_key': 'bio-srfp-03',
        'concept_code': 'sv2c-botany-15',
        'front': 'Why is endosperm usually triploid?',
        'back': 'PEN forms from fusion of one male gamete (n) with two polar nuclei (n + n).',
        'explanation': 'Then PEN divides to form endosperm tissue.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Sexual Reproduction in Flowering Plants',
        'class_level': '12',
    },
    {
        'card_key': 'bio-srfp-04',
        'concept_code': 'sv2c-botany-15',
        'front': 'Define syngamy.',
        'back': 'Fusion of male gamete with the egg cell to form the zygote.',
        'explanation': 'Part of double fertilisation along with triple fusion.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Sexual Reproduction in Flowering Plants',
        'class_level': '12',
    },
    {
        'card_key': 'zoo-ak-01',
        'concept_code': 'ak-levels-of-organisation',
        'front': 'Levels of organisation in animals (NCERT)?',
        'back': 'Cellular (Porifera), tissue (Cnidaria), organ, and organ-system levels.',
        'explanation': 'Complexity increases along this series.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-02',
        'concept_code': 'ak-symmetry',
        'front': 'Differentiate radial and bilateral symmetry.',
        'back': 'Radial: any plane through axis divides into mirrors (Cnidaria, Echinoderm adults); bilateral: single sagittal plane (most animals).',
        'explanation': 'Asymmetry in some Porifera.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-03',
        'concept_code': 'ak-germ-layers',
        'front': 'Diploblastic vs triploblastic?',
        'back': 'Diploblastic: ectoderm + endoderm (Cnidaria); triploblastic: + mesoderm (Platyhelminthes onward).',
        'explanation': 'Mesoderm enables complex organs/coelom.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-04',
        'concept_code': 'ak-coelom',
        'front': 'Acoelomate, pseudocoelomate, coelomate — examples?',
        'back': 'Acoelomate: Platyhelminthes; pseudocoelomate: Aschelminthes; true coelomate: Annelida onward.',
        'explanation': 'Coelom is mesoderm-lined body cavity.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-05',
        'concept_code': 'ak-segmentation-metamerism',
        'front': 'What is metameric segmentation?',
        'back': 'Body divided into serial segments (metameres) with organ repetition; classic in Annelida.',
        'explanation': 'Also seen in Arthropoda and Chordata (modified).',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-06',
        'concept_code': 'ak-porifera-characters',
        'front': 'Salient features of Porifera?',
        'back': 'Cellular level; porous body with canal system; choanocytes; skeleton of spicules/spongin; intracellular digestion.',
        'explanation': 'Mostly marine; hermaphrodite.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-07',
        'concept_code': 'ak-cnidaria-characters',
        'front': 'Cnidaria characters and body forms?',
        'back': 'Tissue level; radial symmetry; cnidoblasts; polyp and medusa forms; incomplete gut (gastrovascular cavity).',
        'explanation': 'Diploblastic.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-08',
        'concept_code': 'ak-platyhelminthes-characters',
        'front': 'Features of Platyhelminthes?',
        'back': 'Triploblastic, acoelomate, bilaterally symmetrical flatworms; organ level; many parasites.',
        'explanation': 'Flame cells for osmoregulation/excretion.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-09',
        'concept_code': 'ak-aschelminthes-characters',
        'front': 'Aschelminthes (Nematoda) characters?',
        'back': 'Pseudocoelomate, cylindrical, complete alimentary canal; often parasitic (Ascaris, Wuchereria).',
        'explanation': 'Sexes usually separate.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-10',
        'concept_code': 'ak-annelida-characters',
        'front': 'Annelida characters?',
        'back': 'Metameric segmentation; true coelom; closed circulation; longitudinal + circular muscles; nephridia.',
        'explanation': 'Examples: Nereis, Pheretima, Hirudinaria.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-11',
        'concept_code': 'ak-arthropoda-characters',
        'front': 'Why is Arthropoda the largest phylum?',
        'back': 'Jointed appendages, chitinous exoskeleton, segmented body; enormous species diversity.',
        'explanation': 'Open circulation; tracheal/book-lung/gills for respiration.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-12',
        'concept_code': 'ak-arthropoda-examples-economic',
        'front': 'Name economically important arthropods (NCERT examples).',
        'back': 'Useful: Apis (honey), Bombyx (silk), Laccifer (lac); vectors/pests: Anopheles, Locusta; living fossil: Limulus.',
        'explanation': 'Also prawns, crabs as food.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-13',
        'concept_code': 'ak-mollusca-characters',
        'front': 'Mollusca body plan essentials?',
        'back': 'Soft body usually with calcareous shell; mantle; muscular foot; unsegmented; open circulation (mostly).',
        'explanation': 'Second largest phylum; e.g. Pila, Octopus, Pinctada.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-14',
        'concept_code': 'ak-echinodermata-characters',
        'front': 'Unique features of Echinodermata?',
        'back': 'Adult radial / larval bilateral symmetry; water vascular system; calcareous endoskeleton; marine.',
        'explanation': 'Examples: Asterias, Echinus, Cucumaria.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-15',
        'concept_code': 'ak-chordate-features',
        'front': 'Fundamental chordate features?',
        'back': 'Notochord, dorsal hollow nerve cord, paired pharyngeal gill slits (at some stage), post-anal tail.',
        'explanation': 'Present at least in embryonic stages.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-16',
        'concept_code': 'ak-protochordates',
        'front': 'Name protochordate subphyla/examples.',
        'back': 'Urochordata (Ascidia, Salpa) and Cephalochordata (Branchiostoma/Amphioxus).',
        'explanation': 'Notochord present in tail (urochordate larva) or throughout (cephalochordate).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-17',
        'concept_code': 'ak-cyclostomata-chondrichthyes-osteichthyes',
        'front': 'Differentiate Chondrichthyes and Osteichthyes briefly.',
        'back': 'Chondrichthyes: cartilaginous endoskeleton, placoid scales, no operculum (usually); Osteichthyes: bony endoskeleton, cycloid/ctenoid scales, operculum, air bladder.',
        'explanation': 'Cyclostomata: jawless (Petromyzon, Myxine).',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-18',
        'concept_code': 'ak-amphibia-reptilia-aves-mammalia',
        'front': 'Key traits: Amphibia vs Reptilia?',
        'back': 'Amphibia: moist skin, dual life, no scales (mostly), external fertilisation often; Reptilia: dry cornified skin with scales, terrestrial adaptations, internal fertilisation, shelled eggs.',
        'explanation': 'Both are cold-blooded (poikilotherms).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-19',
        'concept_code': 'ak-amphibia-reptilia-aves-mammalia',
        'front': 'Features of Aves and Mammalia?',
        'back': 'Aves: feathers, wings, pneumatic bones, 4-chambered heart, oviparous; Mammalia: mammary glands, hair, viviparous (mostly), diaphragm, 4-chambered heart.',
        'explanation': 'Both homeotherms.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-ak-20',
        'concept_code': 'ak-digestive-circulatory-patterns',
        'front': 'Open vs closed circulatory system — phylum examples?',
        'back': 'Open: Arthropoda, Mollusca (mostly); closed: Annelida, Chordata.',
        'explanation': 'Closed: blood confined to vessels; open: haemolymph in sinuses.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Animal Kingdom',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-soa-01',
        'concept_code': 'sv2c-zoology-04',
        'front': 'Name the four basic animal tissue types.',
        'back': 'Epithelial, connective, muscular and neural (nervous) tissue.',
        'explanation': 'Organs are formed by combinations of these tissues.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Structural Organisation in Animals',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-soa-02',
        'concept_code': 'sv2c-zoology-04',
        'front': 'Give one function each of epithelial and connective tissue.',
        'back': 'Epithelial: covering/protection, absorption, secretion; connective: support, binding, transport (blood).',
        'explanation': 'Blood is a fluid connective tissue.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Structural Organisation in Animals',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-soa-03',
        'concept_code': 'sv2c-zoology-05',
        'front': 'Cockroach: type of circulatory system and respiratory organs?',
        'back': 'Open circulation; tracheal system with spiracles for respiration.',
        'explanation': 'Excretion by Malpighian tubules.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Structural Organisation in Animals',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-soa-04',
        'concept_code': 'sv2c-zoology-05',
        'front': 'Frog heart: how many chambers?',
        'back': 'Three chambers — two atria and one ventricle.',
        'explanation': 'Incomplete separation of oxygenated and deoxygenated blood in ventricle.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Structural Organisation in Animals',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-biom-01',
        'concept_code': 'biomolecule-classes',
        'front': 'Major classes of biomolecules in living systems?',
        'back': 'Carbohydrates, proteins, lipids, nucleic acids; also metabolites (primary/secondary).',
        'explanation': 'Ash analysis reveals inorganic elements too.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biomolecules',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-biom-02',
        'concept_code': 'biomolecule-classes',
        'front': 'What are primary vs secondary metabolites?',
        'back': 'Primary: essential for growth (amino acids, sugars, nucleotides); secondary: e.g. alkaloids, pigments, rubber — ecological roles.',
        'explanation': 'Secondary metabolites richer in plants/fungi/microbes.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biomolecules',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-biom-03',
        'concept_code': 'dna-rna',
        'front': 'Structural difference between DNA and RNA (backbone & bases)?',
        'back': 'DNA: deoxyribose, A/T/G/C, usually double helix; RNA: ribose, A/U/G/C, usually single-stranded.',
        'explanation': 'Both are polymers of nucleotides.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biomolecules',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-biom-04',
        'concept_code': 'dna-rna',
        'front': 'Chargaff’s rule for DNA?',
        'back': 'In double-stranded DNA, A = T and G = C (base pairing).',
        'explanation': 'Purines pair with pyrimidines.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biomolecules',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-biom-05',
        'concept_code': 'enzyme-basics',
        'front': 'What is an enzyme? Active site concept?',
        'back': 'Biocatalyst (mostly protein) that speeds reactions; substrate binds at active site forming ES complex.',
        'explanation': 'Lower activation energy.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biomolecules',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-biom-06',
        'concept_code': 'enzyme-basics',
        'front': 'Effect of temperature and pH on enzyme activity?',
        'back': 'Each enzyme has optimum T and pH; extremes denature proteins and reduce activity.',
        'explanation': 'Michaelis–Menten kinetics: rate rises with [S] then saturates.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Biomolecules',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-br-01',
        'concept_code': 'sv2c-zoology-08',
        'front': 'Pathway of air from nostrils to alveoli?',
        'back': 'External nares → nasal chamber → pharynx → larynx → trachea → bronchi → bronchioles → alveolar ducts → alveoli.',
        'explanation': 'Alveoli are the sites of gas exchange.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Breathing and Exchange of Gases',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-br-02',
        'concept_code': 'sv2c-zoology-08',
        'front': 'Why are alveoli efficient for gas exchange?',
        'back': 'Large surface area, thin squamous epithelium, rich capillary network, moist surface.',
        'explanation': 'Fick’s law: diffusion rate ∝ surface area and concentration gradient.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Breathing and Exchange of Gases',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-br-03',
        'concept_code': 'sv2c-zoology-14',
        'front': 'Define tidal volume and vital capacity.',
        'back': 'TV: air inspired/expired in normal breath (~500 mL); VC: maximum air expelled after deepest inspiration (TV+IRV+ERV).',
        'explanation': 'Residual volume remains after forceful expiration.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Breathing and Exchange of Gases',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-br-04',
        'concept_code': 'sv2c-zoology-14',
        'front': 'Approximate residual volume in a healthy adult?',
        'back': 'About 1100–1200 mL (NCERT range).',
        'explanation': 'Prevents lung collapse and allows continuous gas exchange.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Breathing and Exchange of Gases',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-br-05',
        'concept_code': 'sv2c-zoology-09',
        'front': 'What is the Bohr effect?',
        'back': 'Increased CO₂ / decreased pH shifts O₂–Hb dissociation curve right, facilitating O₂ unloading in tissues.',
        'explanation': 'Also favoured by higher temperature.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Breathing and Exchange of Gases',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-br-06',
        'concept_code': 'sv2c-zoology-09',
        'front': 'Form in which CO₂ is mainly transported in blood?',
        'back': 'As bicarbonate (HCO₃⁻) — about 70%; also carbamino-Hb and dissolved CO₂.',
        'explanation': 'Carbonic anhydrase in RBCs catalyses CO₂ + H₂O ⇌ H₂CO₃.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Breathing and Exchange of Gases',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-01',
        'concept_code': 'abo-blood-grouping',
        'front': 'ABO blood groups are based on what?',
        'back': 'Presence/absence of antigens A and B on RBC surface; plasma has antibodies against missing antigens.',
        'explanation': 'AB is universal recipient; O is universal donor (RBCs).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-02',
        'concept_code': 'abo-blood-grouping',
        'front': 'What is Rh factor significance in pregnancy?',
        'back': 'Rh− mother carrying Rh+ foetus may form anti-Rh antibodies → erythroblastosis fetalis in later pregnancies.',
        'explanation': 'Prevented by anti-Rh antibodies given to mother.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-03',
        'concept_code': 'heart-structure',
        'front': 'Chambers of the human heart?',
        'back': 'Four: two atria and two ventricles; double circulation keeps oxygenated and deoxygenated blood separate.',
        'explanation': 'Valves prevent backflow.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-04',
        'concept_code': 'heart-structure',
        'front': 'Names of AV valves on right and left sides?',
        'back': 'Right: tricuspid; left: bicuspid (mitral).',
        'explanation': 'Semilunar valves at bases of pulmonary artery and aorta.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-05',
        'concept_code': 'cardiac-cycle-phases',
        'front': 'Outline major phases of the cardiac cycle.',
        'back': 'Atrial systole → ventricular systole (isovolumetric contraction + ejection) → joint diastole.',
        'explanation': 'About 0.8 s in a resting adult (~72 beats/min).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-06',
        'concept_code': 'sv2c-zoology-12',
        'front': 'What do P, QRS and T waves represent on ECG?',
        'back': 'P: atrial depolarisation; QRS: ventricular depolarisation; T: ventricular repolarisation.',
        'explanation': 'Useful in diagnosing conduction abnormalities.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-07',
        'concept_code': 'sv2c-zoology-15',
        'front': 'Pulmonary vs systemic circulation?',
        'back': 'Pulmonary: right ventricle → lungs → left atrium (oxygenation); systemic: left ventricle → body → right atrium.',
        'explanation': 'Human heart is double-circulatory.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-bf-08',
        'concept_code': 'cardiac-cycle-phases',
        'front': 'During ventricular systole, which valves open and which close?',
        'back': 'AV valves close; semilunar valves open (ejection into arteries).',
        'explanation': 'Lub sound associated with AV valve closure.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Biology — Body Fluids and Circulation',
        'class_level': '11',
    },
    {
        'card_key': 'zoo-hr-01',
        'concept_code': 'gonads-ducts',
        'front': 'Male gonads and duct pathway for sperm?',
        'back': 'Testes produce sperm; path: seminiferous tubules → rete testis → vasa efferentia → epididymis → vas deferens → ejaculatory duct → urethra.',
        'explanation': 'Accessory glands: seminal vesicles, prostate, bulbourethral.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Human Reproduction',
        'class_level': '12',
    },
    {
        'card_key': 'zoo-hr-02',
        'concept_code': 'gonads-ducts',
        'front': 'Female gonad and site of fertilisation?',
        'back': 'Ovaries produce ova; fertilisation usually in the ampullary–isthmic junction of the fallopian tube.',
        'explanation': 'Uterus is site of implantation and gestation.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Human Reproduction',
        'class_level': '12',
    },
    {
        'card_key': 'zoo-hr-03',
        'concept_code': 'spermatogenesis-oogenesis',
        'front': 'End products of spermatogenesis vs oogenesis?',
        'back': 'Spermatogenesis: four haploid sperms per spermatogonium; oogenesis: one ovum + polar bodies per oogonium.',
        'explanation': 'Unequal cytokinesis conserves cytoplasm in the ovum.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Human Reproduction',
        'class_level': '12',
    },
    {
        'card_key': 'zoo-hr-04',
        'concept_code': 'spermatogenesis-oogenesis',
        'front': 'When is meiosis-II completed in human oogenesis?',
        'back': 'At fertilisation — secondary oocyte completes meiosis-II after sperm entry.',
        'explanation': 'Ovulated stage is secondary oocyte arrested at metaphase II.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Human Reproduction',
        'class_level': '12',
    },
    {
        'card_key': 'zoo-hr-05',
        'concept_code': 'menstrual-phases',
        'front': 'Phases of the menstrual cycle?',
        'back': 'Menstrual, follicular (proliferative), ovulatory, luteal (secretory).',
        'explanation': 'LH surge triggers ovulation around mid-cycle.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Human Reproduction',
        'class_level': '12',
    },
    {
        'card_key': 'zoo-hr-06',
        'concept_code': 'menstrual-phases',
        'front': 'Role of corpus luteum if pregnancy occurs?',
        'back': 'Secretes progesterone (and estrogen) to maintain endometrium until placenta takes over.',
        'explanation': 'Without pregnancy it degenerates → menstruation.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Biology — Human Reproduction',
        'class_level': '12',
    },
]
