"""NCERT Chemistry flashcard seed (Class 11–12) for SEED-V1.

concept_code values must match docs/acquisition/flashcards/SEED-V1/concept_map.json.
Chapter-level source_reference only — no page numbers.
"""

from __future__ import annotations

CARDS: list[dict] = [
    {
        'card_key': 'chem-basic-01',
        'concept_code': 'sv2c-chemistry-01',
        'front': 'State the law of conservation of mass.',
        'back': 'Mass is neither created nor destroyed in a chemical reaction; total mass of reactants equals total mass of products.',
        'explanation': 'Antoine Lavoisier established this foundational law of chemical combination.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-02',
        'concept_code': 'sv2c-chemistry-01',
        'front': 'State the law of definite proportions.',
        'back': 'A pure chemical compound always contains the same elements in a fixed mass ratio, regardless of source or method of preparation.',
        'explanation': 'Proust’s law; e.g. water is always H∶O = 1∶8 by mass.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-03',
        'concept_code': 'sv2c-chemistry-01',
        'front': 'How does the law of multiple proportions differ from definite proportions?',
        'back': 'When two elements form more than one compound, masses of one element combining with a fixed mass of the other are in simple whole-number ratios.',
        'explanation': 'Dalton’s law of multiple proportions; e.g. CO and CO₂.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-04',
        'concept_code': 'sv2c-chemistry-02',
        'front': 'Define one mole.',
        'back': 'The amount of substance that contains exactly 6.022 × 10²³ elementary entities (Avogadro’s number).',
        'explanation': 'SI base unit mole; entities may be atoms, molecules, ions, electrons, etc.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-05',
        'concept_code': 'sv2c-chemistry-02',
        'front': 'What is molar mass?',
        'back': 'Mass of one mole of a substance, numerically equal to relative atomic/molecular mass in g mol⁻¹.',
        'explanation': 'E.g. molar mass of H₂O = 18 g mol⁻¹.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-06',
        'concept_code': 'sv2c-chemistry-02',
        'front': 'Relate moles, mass and molar mass.',
        'back': 'n = m / M, where n is amount in mol, m is mass, M is molar mass.',
        'explanation': 'Also n = N / N_A relating particle number to moles.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-07',
        'concept_code': 'sv2c-chemistry-03',
        'front': 'What is an empirical formula?',
        'back': 'The simplest whole-number ratio of atoms of each element in a compound.',
        'explanation': 'E.g. glucose C₆H₁₂O₆ has empirical formula CH₂O.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-08',
        'concept_code': 'sv2c-chemistry-03',
        'front': 'How is molecular formula obtained from empirical formula?',
        'back': 'Molecular formula = (empirical formula)ₙ, where n = molecular mass / empirical formula mass.',
        'explanation': 'n must be a positive integer.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-09',
        'concept_code': 'sv2c-chemistry-03',
        'front': 'Outline steps to find empirical formula from percentage composition.',
        'back': 'Convert % to moles (÷ atomic mass); divide by smallest mole number; multiply to clear fractions → simplest ratio.',
        'explanation': 'Assumes 100 g sample so percentages become grams directly.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-10',
        'concept_code': 'sv2c-chemistry-04',
        'front': 'Define molarity (M).',
        'back': 'Moles of solute per litre of solution: M = n_solute / V_solution (in L).',
        'explanation': 'Temperature-dependent because volume changes with T.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-11',
        'concept_code': 'sv2c-chemistry-04',
        'front': 'How does molarity differ from molality?',
        'back': 'Molarity uses litres of solution; molality uses kg of solvent. Molality is temperature-independent.',
        'explanation': 'NCERT emphasises molarity for aqueous concentration in this chapter.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-12',
        'concept_code': 'sv2c-chemistry-05',
        'front': 'What is a limiting reagent?',
        'back': 'The reactant that is completely consumed first and thus limits the amount of product formed.',
        'explanation': 'Other reactants left after reaction are in excess.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-13',
        'concept_code': 'sv2c-chemistry-05',
        'front': 'How do you identify the limiting reagent?',
        'back': 'Compare available moles of each reactant with stoichiometric requirements; the one that yields the least product is limiting.',
        'explanation': 'Use balanced equation mole ratios.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-basic-14',
        'concept_code': 'sv2c-chemistry-05',
        'front': 'Why must the equation be balanced before applying stoichiometry?',
        'back': 'Mole ratios come from stoichiometric coefficients; an unbalanced equation gives wrong limiting-reagent and yield results.',
        'explanation': 'Mass and atom balance are prerequisites for quantitative analysis.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Some Basic Concepts of Chemistry',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-01',
        'concept_code': 'sv2c-chemistry-06',
        'front': 'State Bohr’s first postulate for the hydrogen atom.',
        'back': 'Electrons revolve in certain discrete (stationary) orbits without radiating energy.',
        'explanation': 'Only orbits with angular momentum mvr = nh/2π are allowed.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-02',
        'concept_code': 'sv2c-chemistry-06',
        'front': 'How does Bohr’s model explain the hydrogen emission spectrum?',
        'back': 'Electron jumps from higher to lower orbit emit photons of energy ΔE = E₂ − E₁ = hν, giving discrete lines.',
        'explanation': 'Rydberg formula for H lines follows from Bohr energy levels.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-03',
        'concept_code': 'sv2c-chemistry-06',
        'front': 'Name the spectral series of hydrogen in the visible region.',
        'back': 'Balmer series (transitions ending at n = 2).',
        'explanation': 'Lyman → UV (n=1); Paschen, Brackett, Pfund → IR.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-04',
        'concept_code': 'sv2c-chemistry-07',
        'front': 'List the four quantum numbers and what each specifies.',
        'back': 'n: principal (shell/size); l: azimuthal (subshell/shape); mₗ: magnetic (orbital orientation); mₛ: spin.',
        'explanation': 'n = 1,2,3…; l = 0 to n−1; mₗ = −l to +l; mₛ = ±½.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-05',
        'concept_code': 'sv2c-chemistry-07',
        'front': 'What values of l correspond to s, p, d and f orbitals?',
        'back': 's: l=0; p: l=1; d: l=2; f: l=3.',
        'explanation': 'Number of orbitals in a subshell = 2l + 1.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-06',
        'concept_code': 'sv2c-chemistry-07',
        'front': 'Can two electrons in an atom have identical values of all four quantum numbers?',
        'back': 'No — Pauli exclusion principle forbids it.',
        'explanation': 'At most two electrons per orbital, with opposite spins.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-07',
        'concept_code': 'sv2c-chemistry-08',
        'front': 'State the Aufbau principle.',
        'back': 'Electrons occupy orbitals in order of increasing energy (roughly n+l rule).',
        'explanation': 'Lower energy orbitals fill before higher ones.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-08',
        'concept_code': 'sv2c-chemistry-08',
        'front': 'State Hund’s rule of maximum multiplicity.',
        'back': 'In degenerate orbitals, electrons occupy singly with parallel spins before pairing.',
        'explanation': 'Minimises electron–electron repulsion.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-09',
        'concept_code': 'sv2c-chemistry-08',
        'front': 'Write the ground-state electronic configuration of chromium (Z=24).',
        'back': 'Cr: [Ar] 3d⁵ 4s¹ (exception to simple Aufbau).',
        'explanation': 'Half-filled d⁵ with 4s¹ is more stable than 3d⁴ 4s².',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-10',
        'concept_code': 'sv2c-chemistry-09',
        'front': 'State two key observations of the photoelectric effect.',
        'back': 'No electrons below threshold frequency ν₀; kinetic energy of photoelectrons depends on frequency, not intensity.',
        'explanation': 'Number of photoelectrons increases with intensity above threshold.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-11',
        'concept_code': 'sv2c-chemistry-09',
        'front': 'Write Einstein’s photoelectric equation.',
        'back': 'hν = ϕ + ½mv²_max, where ϕ = hν₀ is the work function.',
        'explanation': 'Photon energy goes to overcoming work function plus KE of electron.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-12',
        'concept_code': 'sv2c-chemistry-10',
        'front': 'Describe the shape of an s orbital and a p orbital.',
        'back': 's: spherically symmetric; p: dumbbell-shaped along x, y or z.',
        'explanation': 'd orbitals have more complex cloverleaf/doughnut shapes.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-13',
        'concept_code': 'sv2c-chemistry-10',
        'front': 'What is a node in an orbital?',
        'back': 'A region where the probability density of finding the electron is zero.',
        'explanation': 'Radial nodes = n − l − 1; angular nodes = l.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-atom-14',
        'concept_code': 'sv2c-chemistry-10',
        'front': 'How many radial nodes does a 3p orbital have?',
        'back': 'One (n−l−1 = 3−1−1 = 1).',
        'explanation': 'It also has one angular node (l = 1).',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Structure of Atom',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-01',
        'concept_code': 'vsepr-theory',
        'front': 'What does VSEPR theory predict?',
        'back': 'Molecular geometry from repulsion among electron pairs (bonding + lone pairs) around the central atom.',
        'explanation': 'Lone-pair–lone-pair > lone-pair–bond-pair > bond-pair–bond-pair repulsion.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-02',
        'concept_code': 'vsepr-theory',
        'front': 'Why is the bond angle in H₂O less than in CH₄?',
        'back': 'Oxygen has two lone pairs that compress the H–O–H angle (~104.5°) below the tetrahedral 109.5°.',
        'explanation': 'CH₄ has four bonding pairs and no lone pairs on carbon.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-03',
        'concept_code': 'vsepr-theory',
        'front': 'Predict the shape of BF₃ and of NH₃.',
        'back': 'BF₃: trigonal planar; NH₃: trigonal pyramidal.',
        'explanation': 'BF₃ has 3 bp, 0 lp; NH₃ has 3 bp, 1 lp on N.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-04',
        'concept_code': 'sp-sp2-sp3',
        'front': 'What is hybridisation?',
        'back': 'Mixing of atomic orbitals of similar energy to form equivalent hybrid orbitals for bonding.',
        'explanation': 'Explains geometry of molecules like CH₄, C₂H₄, C₂H₂.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-05',
        'concept_code': 'sp-sp2-sp3',
        'front': 'Give hybridisation and geometry for CH₄, BF₃ and BeCl₂.',
        'back': 'CH₄: sp³, tetrahedral; BF₃: sp², trigonal planar; BeCl₂: sp, linear.',
        'explanation': 'Number of hybrid orbitals = number of σ bonds + lone pairs on central atom (steric number).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-06',
        'concept_code': 'sp-sp2-sp3',
        'front': 'What is the hybridisation of carbon in ethene and ethyne?',
        'back': 'Ethene (C₂H₄): sp²; ethyne (C₂H₂): sp.',
        'explanation': 'Remaining p orbitals form π bonds.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-07',
        'concept_code': 'lattice-energy',
        'front': 'Define lattice enthalpy (lattice energy concept).',
        'back': 'Enthalpy change when one mole of an ionic crystal separates into gaseous ions (or the reverse formation process, with opposite sign).',
        'explanation': 'Higher lattice energy → more stable ionic solid.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-08',
        'concept_code': 'lattice-energy',
        'front': 'How do ion charge and size affect lattice energy?',
        'back': 'Higher ionic charges and smaller ionic radii increase lattice energy.',
        'explanation': 'From Coulomb’s law: attraction ∝ |q₁q₂|/r.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-09',
        'concept_code': 'lattice-energy',
        'front': 'Why is MgO’s lattice energy much higher than NaCl’s?',
        'back': 'Mg²⁺ and O²⁻ have higher charges (and smaller sizes) than Na⁺ and Cl⁻.',
        'explanation': 'Charge factor dominates lattice energy comparison.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-10',
        'concept_code': 'sv2c-chemistry-14',
        'front': 'How does electronegativity difference relate to bond type?',
        'back': 'Large ΔEN → ionic character; small ΔEN → covalent; intermediate → polar covalent.',
        'explanation': 'No sharp cutoff; bonding is a continuum.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-11',
        'concept_code': 'sv2c-chemistry-14',
        'front': 'What is a polar covalent bond?',
        'back': 'A covalent bond with unequal sharing of electrons due to electronegativity difference, creating partial charges.',
        'explanation': 'E.g. H–Cl; dipole moment points toward more electronegative atom.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-bond-12',
        'concept_code': 'sv2c-chemistry-14',
        'front': 'Why is HF more polar than HCl?',
        'back': 'Fluorine is more electronegative than chlorine, so ΔEN(H–F) > ΔEN(H–Cl).',
        'explanation': 'Bond polarity scales with electronegativity difference (and bond length).',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Chemical Bonding and Molecular Structure',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-01',
        'concept_code': 'sv2c-chemistry-16',
        'front': 'State the first law of thermodynamics (chemistry convention).',
        'back': 'ΔU = q + w, where ΔU is change in internal energy, q heat, w work.',
        'explanation': 'NCERT uses the sign convention where work done on the system is positive.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-02',
        'concept_code': 'sv2c-chemistry-16',
        'front': 'For expansion work against constant external pressure, write w.',
        'back': 'w = −P_ext ΔV (system does work; w negative in chemistry convention when expansion).',
        'explanation': 'Note: NCERT presents w = −P_ext ΔV for expansion work.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-03',
        'concept_code': 'sv2c-chemistry-16',
        'front': 'Is internal energy a state function? Is heat?',
        'back': 'U is a state function; q and w are path functions.',
        'explanation': 'ΔU depends only on initial and final states.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-04',
        'concept_code': 'sv2c-chemistry-17',
        'front': 'Relate ΔH and ΔU for a reaction involving ideal gases.',
        'back': 'ΔH = ΔU + Δn_g RT, where Δn_g = moles of gaseous products − gaseous reactants.',
        'explanation': 'At constant pressure, H = U + PV.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-05',
        'concept_code': 'sv2c-chemistry-17',
        'front': 'When is ΔH ≈ ΔU for a reaction?',
        'back': 'When Δn_g ≈ 0 (no net change in gas moles), or for condensed-phase reactions with negligible volume change.',
        'explanation': 'E.g. many reactions with only solids/liquids.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-06',
        'concept_code': 'sv2c-chemistry-17',
        'front': 'For N₂(g) + 3H₂(g) → 2NH₃(g), is ΔH greater or less than ΔU?',
        'back': 'Δn_g = −2 < 0, so ΔH = ΔU + Δn_g RT < ΔU.',
        'explanation': 'Enthalpy change is more negative than internal energy change at same T.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-07',
        'concept_code': 'sv2c-chemistry-18',
        'front': 'State Hess’s law.',
        'back': 'The total enthalpy change of a reaction is the same whether it occurs in one step or several steps.',
        'explanation': 'Enthalpy is a state function.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-08',
        'concept_code': 'sv2c-chemistry-18',
        'front': 'How is Hess’s law used to find Δ_rH°?',
        'back': 'Combine known enthalpy changes (formation, combustion, etc.) algebraically so reactants and products match the target reaction.',
        'explanation': 'Reverse a reaction → change sign of ΔH; multiply → scale ΔH.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-09',
        'concept_code': 'sv2c-chemistry-18',
        'front': 'Express Δ_rH° using standard enthalpies of formation.',
        'back': 'Δ_rH° = Σ ν_p Δ_fH°(products) − Σ ν_r Δ_fH°(reactants).',
        'explanation': 'Δ_fH° of an element in its standard state is zero.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-10',
        'concept_code': 'sv2c-chemistry-19',
        'front': 'State the second law of thermodynamics qualitatively.',
        'back': 'Spontaneous processes increase the entropy of the universe; heat cannot spontaneously flow from cold to hot.',
        'explanation': 'For an isolated system, ΔS_universe > 0 for irreversible spontaneous change.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-11',
        'concept_code': 'sv2c-chemistry-19',
        'front': 'Define Gibbs energy change and its spontaneity criterion.',
        'back': 'ΔG = ΔH − TΔS; process is spontaneous (at constant T, P) if ΔG < 0.',
        'explanation': 'At equilibrium ΔG = 0.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-thermo-12',
        'concept_code': 'sv2c-chemistry-19',
        'front': 'When can an endothermic reaction (ΔH > 0) still be spontaneous?',
        'back': 'If ΔS > 0 and T is high enough that TΔS > ΔH, making ΔG < 0.',
        'explanation': 'Entropy-driven spontaneous processes.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Thermodynamics',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-01',
        'concept_code': 'equilibrium-constant',
        'front': 'Define Kc for aA + bB ⇌ cC + dD.',
        'back': 'Kc = [C]^c [D]^d / ([A]^a [B]^b) at equilibrium, with concentrations in mol L⁻¹.',
        'explanation': 'Kc is constant at a given temperature.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-02',
        'concept_code': 'equilibrium-constant',
        'front': 'Relate Kp and Kc.',
        'back': 'Kp = Kc (RT)^{Δn}, where Δn = (c+d) − (a+b) for gaseous moles.',
        'explanation': 'Partial pressures in bar (or atm as per NCERT context).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-03',
        'concept_code': 'equilibrium-constant',
        'front': 'What does a very large Kc imply?',
        'back': 'Equilibrium lies far toward products; reactants are largely converted.',
        'explanation': 'Small Kc means reactants predominate at equilibrium.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-04',
        'concept_code': 'sv2c-chemistry-21',
        'front': 'State Le Chatelier’s principle.',
        'back': 'If a system at equilibrium is disturbed, it shifts to counteract the disturbance.',
        'explanation': 'Applies to changes in concentration, pressure/volume, and temperature.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-05',
        'concept_code': 'sv2c-chemistry-21',
        'front': 'Effect of increasing pressure on N₂ + 3H₂ ⇌ 2NH₃?',
        'back': 'Equilibrium shifts toward fewer gas moles (forward, toward NH₃).',
        'explanation': 'Δn_g = −2; higher P favours product side.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-06',
        'concept_code': 'sv2c-chemistry-21',
        'front': 'How does temperature affect K for an exothermic reaction?',
        'back': 'Increasing T decreases K (equilibrium shifts left).',
        'explanation': 'Heat treated as a product for exothermic equilibria.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-07',
        'concept_code': 'ph-and-kw',
        'front': 'Define pH.',
        'back': 'pH = −log₁₀[H⁺] (or more precisely −log₁₀ a_H⁺).',
        'explanation': 'At 298 K, neutral water has pH = 7.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-08',
        'concept_code': 'ph-and-kw',
        'front': 'What is Kw, the ionic product of water?',
        'back': 'Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ at 298 K.',
        'explanation': 'Kw increases with temperature.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-09',
        'concept_code': 'ph-and-kw',
        'front': 'Relate pH and pOH at 298 K.',
        'back': 'pH + pOH = 14 (= pKw).',
        'explanation': 'From Kw = [H⁺][OH⁻] = 10⁻¹⁴.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-10',
        'concept_code': 'sv2c-chemistry-23',
        'front': 'State the Brønsted–Lowry definition of acids and bases.',
        'back': 'Acid: proton (H⁺) donor; base: proton acceptor.',
        'explanation': 'Applies in aqueous and non-aqueous solvents.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-11',
        'concept_code': 'sv2c-chemistry-23',
        'front': 'What is a conjugate acid–base pair?',
        'back': 'Two species differing by one proton; e.g. HA and A⁻, or B and BH⁺.',
        'explanation': 'Stronger acid ↔ weaker conjugate base.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-12',
        'concept_code': 'sv2c-chemistry-23',
        'front': 'Identify the conjugate base of H₂SO₄ and conjugate acid of NH₃.',
        'back': 'Conjugate base of H₂SO₄: HSO₄⁻; conjugate acid of NH₃: NH₄⁺.',
        'explanation': 'Remove H⁺ from acid; add H⁺ to base.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-13',
        'concept_code': 'ksp-basics',
        'front': 'Define solubility product Ksp for a sparingly soluble salt.',
        'back': 'Ksp is the equilibrium constant for dissolution into ions; for AxBy: Ksp = [A]^x [B]^y.',
        'explanation': 'Applies to saturated solutions of sparingly soluble salts.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-14',
        'concept_code': 'ksp-basics',
        'front': 'When does precipitation occur in terms of ionic product?',
        'back': 'If ionic product Q > Ksp, precipitation occurs until Q = Ksp.',
        'explanation': 'If Q < Ksp, solution is unsaturated.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-eq-15',
        'concept_code': 'ksp-basics',
        'front': 'For AgCl, write Ksp and relate to solubility s (mol L⁻¹).',
        'back': 'AgCl(s) ⇌ Ag⁺ + Cl⁻; Ksp = [Ag⁺][Cl⁻] = s² (in pure water).',
        'explanation': 'Common ion decreases solubility (Le Chatelier).',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Equilibrium',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-01',
        'concept_code': 'sv2c-chemistry-25',
        'front': 'Define oxidation number (oxidation state).',
        'back': 'A hypothetical charge on an atom if electrons in bonds were assigned to the more electronegative atom.',
        'explanation': 'Useful bookkeeping for redox changes.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-02',
        'concept_code': 'sv2c-chemistry-25',
        'front': 'Oxidation number of oxygen in most compounds? Exceptions?',
        'back': 'Usually −2; exceptions include peroxides (−1) and OF₂ (+2).',
        'explanation': 'Fluorine is always −1 in compounds.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-03',
        'concept_code': 'sv2c-chemistry-25',
        'front': 'What is the oxidation number of S in H₂SO₄?',
        'back': '+6 (2(+1) + x + 4(−2) = 0 ⇒ x = +6).',
        'explanation': 'Sum of oxidation numbers equals charge on species.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-04',
        'concept_code': 'sv2c-chemistry-26',
        'front': 'Define oxidising and reducing agents.',
        'back': 'Oxidising agent: accepts electrons / is reduced; reducing agent: donates electrons / is oxidised.',
        'explanation': 'In a redox reaction both processes occur together.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-05',
        'concept_code': 'sv2c-chemistry-26',
        'front': 'In Zn + Cu²⁺ → Zn²⁺ + Cu, identify oxidising and reducing agents.',
        'back': 'Cu²⁺ is oxidising agent (reduced); Zn is reducing agent (oxidised).',
        'explanation': 'Classic displacement redox.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-06',
        'concept_code': 'sv2c-chemistry-26',
        'front': 'Can the same element be both oxidised and reduced in one reaction?',
        'back': 'Yes — disproportionation: same species undergoes oxidation and reduction.',
        'explanation': 'E.g. 2H₂O₂ → 2H₂O + O₂.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-07',
        'concept_code': 'sv2c-chemistry-27',
        'front': 'Name two methods to balance redox equations.',
        'back': 'Oxidation-number method and half-reaction (ion-electron) method.',
        'explanation': 'Both ensure atom and charge balance.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-08',
        'concept_code': 'sv2c-chemistry-27',
        'front': 'In the ion-electron method, what is balanced in each half-reaction?',
        'back': 'Atoms (often with H₂O/H⁺/OH⁻) and then charge by adding electrons.',
        'explanation': 'Multiply half-reactions so electrons cancel when combined.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-09',
        'concept_code': 'sv2c-chemistry-27',
        'front': 'Why must electrons lost equal electrons gained?',
        'back': 'Charge and mass conservation: total oxidation and reduction are complementary.',
        'explanation': 'Scaling half-reactions enforces equal electron transfer.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-10',
        'concept_code': 'sv2c-chemistry-28',
        'front': 'List four types of redox reactions named in NCERT.',
        'back': 'Combination, decomposition, displacement, and disproportionation.',
        'explanation': 'Classification based on how oxidation states change.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-11',
        'concept_code': 'sv2c-chemistry-28',
        'front': 'Give one example of a displacement redox reaction.',
        'back': 'CuSO₄ + Zn → ZnSO₄ + Cu (Zn displaces Cu²⁺).',
        'explanation': 'More reactive metal reduces ion of less reactive metal.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-redox-12',
        'concept_code': 'sv2c-chemistry-28',
        'front': 'Why is 2KClO₃ → 2KCl + 3O₂ a decomposition redox reaction?',
        'back': 'One compound breaks into simpler species; Cl is reduced and O is oxidised.',
        'explanation': 'Oxidation numbers of Cl and O change.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Redox Reactions',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-01',
        'concept_code': 'homologous-series',
        'front': 'What is a homologous series?',
        'back': 'A family of organic compounds with the same functional group and general formula, differing by −CH₂− units.',
        'explanation': 'Members show gradual change in physical properties.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-02',
        'concept_code': 'homologous-series',
        'front': 'Give the general formula of alkanes and alkenes.',
        'back': 'Alkanes: CₙH₂ₙ₊₂; alkenes: CₙH₂ₙ (acyclic).',
        'explanation': 'Alkynes (acyclic): CₙH₂ₙ₋₂.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-03',
        'concept_code': 'homologous-series',
        'front': 'Why do boiling points increase down a homologous series?',
        'back': 'Larger molecules have stronger van der Waals forces.',
        'explanation': 'Branching typically lowers boiling point vs straight chain.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-04',
        'concept_code': 'sv2c-chemistry-32',
        'front': 'What is the longest chain rule in IUPAC naming?',
        'back': 'Select the longest continuous carbon chain containing the principal functional group as the parent chain.',
        'explanation': 'Number to give lowest locants to principal group / substituents as per rules.',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-05',
        'concept_code': 'sv2c-chemistry-32',
        'front': 'Name CH₃–CH₂–CH₂–OH by IUPAC.',
        'back': 'Propan-1-ol.',
        'explanation': 'Three-carbon chain with −OH at C-1.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-06',
        'concept_code': 'sv2c-chemistry-32',
        'front': 'Give the IUPAC name of (CH₃)₂CH–CH₂–CH₃.',
        'back': '2-Methylbutane.',
        'explanation': 'Longest chain has 4 C; methyl branch at C-2.',
        'difficulty': 'hard',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-07',
        'concept_code': 'structural-isomerism',
        'front': 'What is structural isomerism?',
        'back': 'Compounds with the same molecular formula but different connectivity of atoms.',
        'explanation': 'Includes chain, position, functional, metamerism, tautomerism (as taught).',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-08',
        'concept_code': 'structural-isomerism',
        'front': 'Give two structural isomers of C₄H₁₀.',
        'back': 'Butane (n-butane) and 2-methylpropane (isobutane).',
        'explanation': 'Chain isomerism.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-09',
        'concept_code': 'structural-isomerism',
        'front': 'Are ethanol and dimethyl ether structural isomers?',
        'back': 'Yes — both C₂H₆O but different functional groups (alcohol vs ether).',
        'explanation': 'Functional group isomerism.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-10',
        'concept_code': 'inductive-mesomeric',
        'front': 'What is the inductive effect (−I / +I)?',
        'back': 'Permanent polarisation of a σ bond by an electronegative or electropositive atom/group, transmitted along the chain.',
        'explanation': '−I: electron-withdrawing (e.g. −NO₂, −Cl); +I: electron-releasing (alkyl).',
        'difficulty': 'easy',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-11',
        'concept_code': 'inductive-mesomeric',
        'front': 'What is the resonance (mesomeric) effect?',
        'back': 'Delocalisation of π electrons (or lone pairs) through conjugated systems, shown by resonance structures.',
        'explanation': '−R/−M or +R/+M depending on electron withdrawal or donation via π system.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-12',
        'concept_code': 'inductive-mesomeric',
        'front': 'Why is the −OH group activating and ortho/para-directing in electrophilic aromatic substitution (qualitative)?',
        'back': 'Lone pairs on oxygen conjugate with the ring (+R), increasing electron density at o/p positions.',
        'explanation': 'Despite −I of oxygen, resonance donation dominates for phenol.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-13',
        'concept_code': 'homologous-series',
        'front': 'What is a functional group?',
        'back': 'An atom or group of atoms that determines the characteristic chemical properties of an organic compound.',
        'explanation': 'E.g. −OH (alcohol), −COOH (carboxylic acid), −CHO (aldehyde).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-org-14',
        'concept_code': 'structural-isomerism',
        'front': 'Differentiate chain isomerism and position isomerism briefly.',
        'back': 'Chain: different carbon skeleton; position: same skeleton/functional group type but different location of group/unsaturation.',
        'explanation': 'E.g. butan-1-ol vs butan-2-ol is position isomerism.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 11 Chemistry — Organic Chemistry: Some Basic Principles and Techniques',
        'class_level': '11',
    },
    {
        'card_key': 'chem-echem-01',
        'concept_code': 'sv2c-chemistry-33',
        'front': 'What is a Daniell cell?',
        'back': 'A galvanic cell: Zn|Zn²⁺ || Cu²⁺|Cu; Zn oxidised at anode, Cu²⁺ reduced at cathode.',
        'explanation': 'Converts chemical energy of Zn + Cu²⁺ → Zn²⁺ + Cu into electrical energy.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-02',
        'concept_code': 'sv2c-chemistry-33',
        'front': 'How is a galvanic cell represented in cell notation?',
        'back': 'Anode (oxidation) | anode ion || cathode ion | cathode (reduction); || is salt bridge.',
        'explanation': 'E.g. Zn(s)|Zn²⁺(aq)||Cu²⁺(aq)|Cu(s).',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-03',
        'concept_code': 'sv2c-chemistry-33',
        'front': 'In a Daniell cell, which electrode is negative?',
        'back': 'Zinc electrode (anode) is negative; copper (cathode) is positive.',
        'explanation': 'Electrons flow externally from Zn to Cu.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-04',
        'concept_code': 'sv2c-chemistry-34',
        'front': 'How does EMF of a cell depend on concentration qualitatively?',
        'back': 'EMF increases when reactant concentrations (or pressures) increase and product concentrations decrease.',
        'explanation': 'Nernst equation: E = E° − (RT/nF) ln Q.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-05',
        'concept_code': 'sv2c-chemistry-34',
        'front': 'What happens to Daniell cell EMF if [Cu²⁺] is increased?',
        'back': 'EMF increases (Q decreases for Zn + Cu²⁺ → Zn²⁺ + Cu).',
        'explanation': 'Favouring reactants side of Q raises E.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-06',
        'concept_code': 'sv2c-chemistry-34',
        'front': 'At equilibrium, what is the cell EMF?',
        'back': 'E = 0; Q = K; no net driving force for current.',
        'explanation': 'E° = (RT/nF) ln K relates standard EMF to equilibrium constant.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-07',
        'concept_code': 'sv2c-chemistry-35',
        'front': 'Define molar conductivity Λₘ.',
        'back': 'Λₘ = κ / c — conductivity of the electrolyte divided by molar concentration.',
        'explanation': 'Units commonly S cm² mol⁻¹.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-08',
        'concept_code': 'sv2c-chemistry-35',
        'front': 'How does Λₘ of a strong electrolyte vary with dilution?',
        'back': 'Increases slightly with dilution and approaches a limiting value Λₘ°.',
        'explanation': 'Interionic interactions weaken on dilution.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-09',
        'concept_code': 'sv2c-chemistry-35',
        'front': 'State Kohlrausch’s law of independent migration of ions.',
        'back': 'Λₘ° = ν₊ λ₊° + ν₋ λ₋° — limiting molar conductivity is sum of ionic contributions.',
        'explanation': 'Used to find Λₘ° of weak electrolytes from strong ones.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-10',
        'concept_code': 'sv2c-chemistry-33',
        'front': 'Role of the salt bridge in a galvanic cell?',
        'back': 'Maintains electrical neutrality by ion flow; completes the circuit without mixing electrolytes.',
        'explanation': 'Prevents liquid junction potential buildup that would stop the cell.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-11',
        'concept_code': 'sv2c-chemistry-35',
        'front': 'Why does Λₘ of a weak electrolyte rise sharply on dilution?',
        'back': 'Degree of dissociation α increases on dilution, so more ions form.',
        'explanation': 'Ostwald dilution law links α and concentration for weak electrolytes.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
    {
        'card_key': 'chem-echem-12',
        'concept_code': 'sv2c-chemistry-34',
        'front': 'Write the qualitative form of the Nernst equation for a cell.',
        'back': 'E_cell = E°_cell − (RT/nF) ln Q (or 2.303RT/nF log Q).',
        'explanation': 'Q is the reaction quotient for the cell reaction.',
        'difficulty': 'medium',
        'source': 'NCERT',
        'source_reference': 'NCERT Class 12 Chemistry — Electrochemistry',
        'class_level': '12',
    },
]
