"""NCERT Physics flashcard seed (Class 11–12) for SEED-V1.

concept_code values must match docs/acquisition/flashcards/SEED-V1/concept_map.json
(subject=PHYSICS). Chapter-level source_reference only — no page numbers.
"""

from __future__ import annotations

CARDS: list[dict] = [
    # ── Units and Measurement (Class 11) ──────────────────────────────────
    {
        "card_key": "phy-units-01",
        "concept_code": "si-base-and-derived-units",
        "front": "How many SI base units are there, and name three of them.",
        "back": "Seven SI base units. Examples: metre (length), kilogram (mass), second (time), ampere, kelvin, mole, candela.",
        "explanation": "All other SI units are derived from these seven base units by multiplication or division.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-02",
        "concept_code": "si-base-and-derived-units",
        "front": "What is the SI unit of force expressed in base units?",
        "back": "newton (N) = kg·m·s⁻²",
        "explanation": "From F = ma: mass × acceleration gives kg·m·s⁻².",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-03",
        "concept_code": "dimensional-formulae",
        "front": "Write the dimensional formula of force.",
        "back": "[F] = [M L T⁻²]",
        "explanation": "Force = mass × acceleration; acceleration has dimensions L T⁻².",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-04",
        "concept_code": "dimensional-formulae",
        "front": "Give the dimensional formula of Planck’s constant h.",
        "back": "[h] = [M L² T⁻¹]",
        "explanation": "From E = hν: energy [M L² T⁻²] divided by frequency [T⁻¹] yields [M L² T⁻¹].",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-05",
        "concept_code": "dimensional-analysis-applications",
        "front": "Name three uses of dimensional analysis.",
        "back": "Check equation consistency; convert units between systems; derive relations among physical quantities (up to a dimensionless constant).",
        "explanation": "It cannot fix numerical constants or distinguish quantities with the same dimensions.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-06",
        "concept_code": "dimensional-analysis-applications",
        "front": "Why can dimensional analysis not determine the numerical factor in T = 2π√(l/g)?",
        "back": "2π is dimensionless; dimensions alone cannot fix pure numbers.",
        "explanation": "Dimensional methods give the form √(l/g) but not the constant 2π.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-07",
        "concept_code": "significant-figures",
        "front": "How many significant figures are in 0.05020?",
        "back": "Four (5, 0, 2, 0).",
        "explanation": "Leading zeros after the decimal are not significant; trailing zeros after a non-zero digit in a decimal are significant.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    {
        "card_key": "phy-units-08",
        "concept_code": "significant-figures",
        "front": "In multiplication/division, how is the number of significant figures in the result decided?",
        "back": "Result has as many significant figures as the factor with the fewest significant figures.",
        "explanation": "For addition/subtraction, the least precise decimal place (not significant-figure count) limits the result.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Units and Measurement",
        "class_level": "11",
    },
    # ── Kinematics (Class 11) ─────────────────────────────────────────────
    {
        "card_key": "phy-kin-01",
        "concept_code": "kinematic-equations",
        "front": "State the three kinematic equations for constant acceleration along a straight line.",
        "back": "v = u + at; s = ut + ½at²; v² = u² + 2as.",
        "explanation": "Valid only when acceleration is constant (uniform).",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Straight Line / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-02",
        "concept_code": "kinematic-equations",
        "front": "A body starts from rest with constant a. Express displacement in time t.",
        "back": "s = ½at²",
        "explanation": "With u = 0, s = ut + ½at² reduces to ½at².",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Straight Line / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-03",
        "concept_code": "instantaneous-velocity-acceleration",
        "front": "Define instantaneous velocity.",
        "back": "Limit of Δx/Δt as Δt → 0; equal to dx/dt at that instant.",
        "explanation": "It is the slope of the x–t graph at the chosen time.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Straight Line / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-04",
        "concept_code": "instantaneous-velocity-acceleration",
        "front": "How is instantaneous acceleration related to the v–t graph?",
        "back": "It is the slope of the velocity–time graph at that instant (a = dv/dt).",
        "explanation": "Area under the v–t curve gives displacement.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Straight Line / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-05",
        "concept_code": "relative-velocity-1d",
        "front": "Two cars A and B move along the same line with velocities v_A and v_B. What is velocity of A relative to B?",
        "back": "v_AB = v_A − v_B",
        "explanation": "In one dimension, relative velocity is the algebraic difference of velocities.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Straight Line / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-06",
        "concept_code": "relative-velocity-1d",
        "front": "When is the relative velocity of two objects zero in 1D?",
        "back": "When both have the same velocity (same speed and direction).",
        "explanation": "Then v_A − v_B = 0; they stay a fixed distance apart if moving on the same line.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Straight Line / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-07",
        "concept_code": "vectors-in-plane-motion",
        "front": "If two vectors of equal magnitude A make angle θ, what is the magnitude of their resultant?",
        "back": "|R| = 2A cos(θ/2)",
        "explanation": "From |R|² = A² + A² + 2A·A cos θ = 2A²(1 + cos θ) = 4A² cos²(θ/2).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-08",
        "concept_code": "vectors-in-plane-motion",
        "front": "Resolve a vector A into components along x and y for angle θ with the x-axis.",
        "back": "A_x = A cos θ, A_y = A sin θ",
        "explanation": "These rectangular components fully specify the vector in a plane.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-09",
        "concept_code": "projectile-motion",
        "front": "For a projectile launched with speed u at angle θ to horizontal, what is the time of flight (level ground)?",
        "back": "T = (2u sin θ)/g",
        "explanation": "Vertical motion returns to the same height when 0 = (u sin θ)t − ½gt².",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-10",
        "concept_code": "projectile-motion",
        "front": "At what projection angle is range maximum for fixed u on level ground?",
        "back": "θ = 45°",
        "explanation": "R = (u² sin 2θ)/g is maximum when sin 2θ = 1 ⇒ 2θ = 90°.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-11",
        "concept_code": "projectile-motion",
        "front": "Write the maximum height of a projectile with launch speed u and angle θ.",
        "back": "H = (u² sin² θ)/(2g)",
        "explanation": "At the top, vertical velocity is zero; use v² = u² − 2gH with u_y = u sin θ.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-12",
        "concept_code": "uniform-circular-motion",
        "front": "What is the magnitude of centripetal acceleration in UCM of radius R and speed v?",
        "back": "a = v²/R = ω²R",
        "explanation": "Direction is always toward the centre, perpendicular to the velocity.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    {
        "card_key": "phy-kin-13",
        "concept_code": "uniform-circular-motion",
        "front": "In uniform circular motion, is acceleration zero? Explain briefly.",
        "back": "No — speed is constant but velocity direction changes, so there is centripetal acceleration.",
        "explanation": "Acceleration is the rate of change of velocity, not merely of speed.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Motion in a Plane / Kinematics",
        "class_level": "11",
    },
    # ── Laws of Motion (Class 11) ─────────────────────────────────────────
    {
        "card_key": "phy-lom-01",
        "concept_code": "newtons-laws",
        "front": "State Newton’s first law of motion.",
        "back": "A body remains at rest or in uniform motion in a straight line unless acted on by an external force.",
        "explanation": "It defines inertia; force is needed to change the state of motion.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-02",
        "concept_code": "newtons-laws",
        "front": "Write Newton’s second law in terms of momentum.",
        "back": "F = dp/dt (rate of change of momentum equals net external force).",
        "explanation": "For constant mass this reduces to F = ma.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-03",
        "concept_code": "newtons-laws",
        "front": "State Newton’s third law.",
        "back": "To every action there is an equal and opposite reaction; forces act on different bodies.",
        "explanation": "Action–reaction pairs never cancel on the same free-body diagram.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-04",
        "concept_code": "conservation-of-momentum",
        "front": "When is the total linear momentum of a system conserved?",
        "back": "When the net external force on the system is zero.",
        "explanation": "Internal forces cancel in pairs by Newton’s third law and do not change total momentum.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-05",
        "concept_code": "conservation-of-momentum",
        "front": "A gun of mass M fires a bullet of mass m with muzzle speed v. Recoil speed of the gun?",
        "back": "V = (m/M)v (opposite to the bullet), if initially at rest and no external horizontal force.",
        "explanation": "Momentum conservation: 0 = MV − mv (signs opposite).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-06",
        "concept_code": "friction",
        "front": "What is the maximum static friction on a body of weight mg on a horizontal surface with coefficient μ_s?",
        "back": "f_max = μ_s N = μ_s mg",
        "explanation": "Static friction adjusts up to μ_s N; kinetic friction is typically μ_k N with μ_k ≤ μ_s.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-07",
        "concept_code": "friction",
        "front": "On an inclined plane of angle θ, what is the condition for a body to just start sliding (μ_s)?",
        "back": "tan θ = μ_s",
        "explanation": "At limiting equilibrium, mg sin θ = μ_s mg cos θ.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-08",
        "concept_code": "friction",
        "front": "Does kinetic friction depend on the area of contact (ideal dry friction model)?",
        "back": "No — within the usual model, f_k = μ_k N depends on normal force and μ_k, not contact area.",
        "explanation": "NCERT presents this as an experimental approximate law for dry sliding friction.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-09",
        "concept_code": "dynamics-uniform-circular-motion",
        "front": "What provides the centripetal force for a car rounding a level unbanked curve of radius R at speed v?",
        "back": "Static friction toward the centre: f ≥ mv²/R (required).",
        "explanation": "Without banking, friction alone supplies centripetal force; if insufficient, the car skids.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-lom-10",
        "concept_code": "dynamics-uniform-circular-motion",
        "front": "For a banked curve of angle θ with negligible friction, what is the design speed?",
        "back": "v = √(Rg tan θ)",
        "explanation": "Horizontal component of normal force supplies mv²/R when N sin θ = mv²/R and N cos θ = mg.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Laws of Motion",
        "class_level": "11",
    },
    # ── Work, Energy and Power (Class 11) ─────────────────────────────────
    {
        "card_key": "phy-wep-01",
        "concept_code": "work-by-a-force",
        "front": "Define work done by a constant force F when displacement is s and angle between them is θ.",
        "back": "W = F·s = Fs cos θ",
        "explanation": "Work is a scalar; it is zero if force is perpendicular to displacement.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-02",
        "concept_code": "work-by-a-force",
        "front": "When is work done by a force negative?",
        "back": "When the angle between force and displacement is obtuse (cos θ < 0), e.g. kinetic friction opposing motion.",
        "explanation": "Negative work means the force removes energy from the system.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-03",
        "concept_code": "work-energy-theorem",
        "front": "State the work–energy theorem.",
        "back": "Net work by all forces equals change in kinetic energy: W_net = ΔK = K_f − K_i.",
        "explanation": "This holds in inertial frames for a particle (or system treated as a particle).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-04",
        "concept_code": "work-energy-theorem",
        "front": "A force does 20 J of work and increases KE by 12 J. What about other forces?",
        "back": "Other forces together do −8 J of work (net work = 12 J).",
        "explanation": "W_net = ΔK; if one force does 20 J, remaining contribution is ΔK − 20 = −8 J.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-05",
        "concept_code": "potential-energy",
        "front": "Write gravitational potential energy near Earth’s surface for height h.",
        "back": "U = mgh (taking U = 0 at the reference level).",
        "explanation": "Only differences in U matter; the zero of potential energy is arbitrary.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-06",
        "concept_code": "potential-energy",
        "front": "Elastic PE of a spring stretched/compressed by x from natural length?",
        "back": "U = ½kx²",
        "explanation": "For an ideal spring with force F = −kx, work stored equals ½kx².",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-07",
        "concept_code": "conservation-mechanical-energy",
        "front": "When is mechanical energy (K + U) conserved?",
        "back": "When only conservative forces do work (or non-conservative work is zero).",
        "explanation": "Friction and air drag typically convert mechanical energy into heat/sound.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-08",
        "concept_code": "conservation-mechanical-energy",
        "front": "A body slides down a frictionless incline. What happens to K + U?",
        "back": "Mechanical energy remains constant; PE converts to KE.",
        "explanation": "Normal force does no work (perpendicular to displacement); gravity is conservative.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-09",
        "concept_code": "power",
        "front": "Define instantaneous power.",
        "back": "P = F·v (rate of doing work at an instant).",
        "explanation": "Average power is total work divided by time interval.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-10",
        "concept_code": "power",
        "front": "SI unit of power and its relation to watt and horsepower (approx)?",
        "back": "Watt (W) = J/s; 1 hp ≈ 746 W.",
        "explanation": "Power measures how fast work is done or energy is transferred.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-11",
        "concept_code": "collisions",
        "front": "Distinguish elastic and inelastic collisions (1D).",
        "back": "Elastic: momentum and kinetic energy both conserved. Inelastic: momentum conserved, KE not (perfectly inelastic: bodies stick).",
        "explanation": "Coefficient of restitution e = 1 (elastic), 0 (perfectly inelastic), 0 < e < 1 (partially inelastic).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    {
        "card_key": "phy-wep-12",
        "concept_code": "collisions",
        "front": "In a 1D elastic collision of equal masses with target at rest, what are final velocities?",
        "back": "Projectile stops; target takes the projectile’s initial velocity (velocities exchanged).",
        "explanation": "From simultaneous conservation of momentum and KE for m₁ = m₂.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Work, Energy and Power",
        "class_level": "11",
    },
    # ── Systems of Particles and Rotational Motion (Class 11) ─────────────
    {
        "card_key": "phy-rot-01",
        "concept_code": "centre-of-mass-system",
        "front": "Define centre of mass for a system of particles.",
        "back": "Weighted average position: R_CM = (Σ m_i r_i)/M, with M = Σ m_i.",
        "explanation": "For a continuous body, integrals replace sums with mass density.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-02",
        "concept_code": "motion-of-centre-of-mass",
        "front": "How does the CM of a system accelerate?",
        "back": "M a_CM = F_ext (net external force).",
        "explanation": "Internal forces cancel in pairs and do not affect CM motion.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-03",
        "concept_code": "rotational-kinematics",
        "front": "Write the angular analogues of v = u + at for constant angular acceleration α.",
        "back": "ω = ω₀ + αt; θ = ω₀t + ½αt²; ω² = ω₀² + 2αθ.",
        "explanation": "Linear and angular kinematic forms match with s↔θ, v↔ω, a↔α.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-04",
        "concept_code": "torque",
        "front": "Define torque of a force about a point.",
        "back": "τ = r × F; magnitude r F sin φ (φ = angle between r and F).",
        "explanation": "Torque is the rotational analogue of force; SI unit N·m.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-05",
        "concept_code": "torque",
        "front": "When is the torque of a force about a point zero?",
        "back": "When the line of action passes through the point (r∥F or lever arm = 0), or F = 0.",
        "explanation": "Moment arm is the perpendicular distance from the point to the force’s line of action.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-06",
        "concept_code": "moment-of-inertia",
        "front": "Define moment of inertia of a system about an axis.",
        "back": "I = Σ m_i r_i² (r_i = perpendicular distance from the axis).",
        "explanation": "It measures rotational inertia; SI unit kg·m².",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-07",
        "concept_code": "moment-of-inertia",
        "front": "Moment of inertia of a thin ring of mass M and radius R about its central axis perpendicular to its plane?",
        "back": "I = MR²",
        "explanation": "All mass elements are at distance R from that axis.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-08",
        "concept_code": "moment-of-inertia",
        "front": "State the parallel-axis theorem.",
        "back": "I = I_CM + Md², where d is distance between parallel axes (one through CM).",
        "explanation": "Applies to any rigid body; axes must be parallel.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-09",
        "concept_code": "dynamics-of-rotational-motion",
        "front": "Write Newton’s second law for rotation about a fixed axis.",
        "back": "τ_net = I α",
        "explanation": "Net external torque equals moment of inertia times angular acceleration.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-10",
        "concept_code": "angular-momentum",
        "front": "Define angular momentum of a particle about a point.",
        "back": "L = r × p; magnitude r p sin φ.",
        "explanation": "For a rigid body about a fixed axis, L = Iω along the axis (for principal axes).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-11",
        "concept_code": "angular-momentum",
        "front": "State the condition for conservation of angular momentum.",
        "back": "If net external torque about a point/axis is zero, L about that point/axis is conserved.",
        "explanation": "Classic example: ice skater pulling arms in — I decreases, ω increases.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    {
        "card_key": "phy-rot-12",
        "concept_code": "angular-momentum",
        "front": "Relation between torque and angular momentum?",
        "back": "τ_ext = dL/dt",
        "explanation": "Analogous to F = dp/dt for linear motion.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Systems of Particles and Rotational Motion",
        "class_level": "11",
    },
    # ── Mechanical Properties of Solids (Class 11) ────────────────────────
    {
        "card_key": "phy-sol-01",
        "concept_code": "stress-strain-definitions",
        "front": "Define longitudinal stress and longitudinal strain.",
        "back": "Stress = F/A; strain = ΔL/L (dimensionless).",
        "explanation": "Stress has dimensions of pressure; SI unit N/m² (pascal).",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-02",
        "concept_code": "stress-strain-definitions",
        "front": "What is Hooke’s law in elasticity?",
        "back": "Within the elastic limit, stress ∝ strain (stress = modulus × strain).",
        "explanation": "The constant of proportionality is the relevant elastic modulus.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-03",
        "concept_code": "youngs-modulus",
        "front": "Define Young’s modulus Y.",
        "back": "Y = (longitudinal stress)/(longitudinal strain) = (F/A)/(ΔL/L)",
        "explanation": "Applies to stretching/compression of rods/wires within the elastic limit.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-04",
        "concept_code": "youngs-modulus",
        "front": "A wire’s length doubles under the same load if cross-section halves. What happens to extension (same Y)?",
        "back": "Extension becomes 4 times (ΔL ∝ L/A).",
        "explanation": "From ΔL = (F L)/(A Y): doubling L and halving A multiplies ΔL by 4.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-05",
        "concept_code": "shear-modulus",
        "front": "Define shear modulus (modulus of rigidity) G.",
        "back": "G = shear stress / shear strain = (F/A)/θ (for small θ in radians).",
        "explanation": "Shear strain is the angular deformation of a face.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-06",
        "concept_code": "bulk-modulus",
        "front": "Define bulk modulus B.",
        "back": "B = −(ΔP)/(ΔV/V); negative sign makes B positive as volume decreases under pressure.",
        "explanation": "Compressibility is 1/B.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-07",
        "concept_code": "stress-strain-curve",
        "front": "On a typical stress–strain curve for a metal, what is the elastic limit / proportional limit region?",
        "back": "Nearly linear portion where Hooke’s law holds; beyond it permanent deformation begins (plastic region).",
        "explanation": "Yield point marks onset of plastic flow; fracture occurs at the breaking stress.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    {
        "card_key": "phy-sol-08",
        "concept_code": "stress-strain-curve",
        "front": "Distinguish ductile and brittle materials via stress–strain behaviour.",
        "back": "Ductile: large plastic strain before fracture. Brittle: little plastic deformation; fracture near elastic limit.",
        "explanation": "Steel is typically ductile; glass/cast iron are relatively brittle.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Solids",
        "class_level": "11",
    },
    # ── Mechanical Properties of Fluids (Class 11) ────────────────────────
    {
        "card_key": "phy-flu-01",
        "concept_code": "hydrostatic-pressure-pascal",
        "front": "Write the hydrostatic pressure at depth h in a liquid of density ρ.",
        "back": "P = P₀ + ρgh (P₀ = pressure at the free surface).",
        "explanation": "Pressure increases linearly with depth for an incompressible fluid at rest.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-02",
        "concept_code": "hydrostatic-pressure-pascal",
        "front": "State Pascal’s law.",
        "back": "Pressure applied to an enclosed fluid is transmitted undiminished to every portion of the fluid and the walls.",
        "explanation": "Basis of hydraulic lifts and brakes.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-03",
        "concept_code": "streamline-flow",
        "front": "What is streamline (laminar) flow?",
        "back": "Flow in which fluid particles follow smooth paths; streamlines do not cross.",
        "explanation": "At a point, velocity is tangent to the streamline; for steady flow, pattern is time-independent.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-04",
        "concept_code": "streamline-flow",
        "front": "State the equation of continuity for incompressible flow in a pipe.",
        "back": "A₁v₁ = A₂v₂ (volume flux conserved).",
        "explanation": "Narrower cross-section ⇒ higher speed for steady incompressible flow.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-05",
        "concept_code": "bernoullis-principle",
        "front": "State Bernoulli’s equation for steady, incompressible, non-viscous flow along a streamline.",
        "back": "P + ½ρv² + ρgh = constant",
        "explanation": "It expresses mechanical energy conservation per unit volume for ideal fluids.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-06",
        "concept_code": "bernoullis-principle",
        "front": "Why does pressure drop where a fluid speeds up in a horizontal pipe (ideal flow)?",
        "back": "From Bernoulli: if h is fixed, increase in ½ρv² must decrease P.",
        "explanation": "This underlies Venturi meters and lift explanations in elementary treatments.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-07",
        "concept_code": "viscosity",
        "front": "Write Newton’s law of viscosity (definition of coefficient η).",
        "back": "F/A = η (dv/dz); η is coefficient of viscosity.",
        "explanation": "Viscous force opposes relative motion between fluid layers.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-08",
        "concept_code": "viscosity",
        "front": "Stokes’ law: viscous drag on a sphere of radius r moving at speed v in a fluid of viscosity η?",
        "back": "F = 6πηrv",
        "explanation": "Used for terminal velocity of small spheres in viscous media.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-09",
        "concept_code": "surface-tension",
        "front": "Define surface tension.",
        "back": "Force per unit length acting tangentially on a line in the liquid surface: S = F/l.",
        "explanation": "Also equal to surface energy per unit area.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    {
        "card_key": "phy-flu-10",
        "concept_code": "surface-tension",
        "front": "Excess pressure inside a soap bubble of radius R and surface tension S?",
        "back": "ΔP = 4S/R (two surfaces).",
        "explanation": "For a liquid drop (one surface), ΔP = 2S/R.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Mechanical Properties of Fluids",
        "class_level": "11",
    },
    # ── Thermodynamics (Class 11) ─────────────────────────────────────────
    {
        "card_key": "phy-thermo-01",
        "concept_code": "zeroth-and-first-law",
        "front": "State the zeroth law of thermodynamics.",
        "back": "If A is in thermal equilibrium with B, and B with C, then A is in thermal equilibrium with C.",
        "explanation": "It justifies temperature as a transitive equilibrium property.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-02",
        "concept_code": "zeroth-and-first-law",
        "front": "Write the first law of thermodynamics.",
        "back": "ΔQ = ΔU + ΔW (heat supplied = rise in internal energy + work done by the system).",
        "explanation": "Sign convention follows NCERT: W is work by the system.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-03",
        "concept_code": "heat-internal-energy-work",
        "front": "For an ideal gas, on what does internal energy U depend?",
        "back": "Only on temperature (for a fixed amount of ideal gas).",
        "explanation": "ΔU = n C_V ΔT for an ideal gas, independent of path.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-04",
        "concept_code": "heat-internal-energy-work",
        "front": "Work done by an ideal gas in a quasi-static isobaric expansion from V₁ to V₂?",
        "back": "W = P(V₂ − V₁) = nR(T₂ − T₁)",
        "explanation": "At constant pressure, W = ∫ P dV = P ΔV.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-05",
        "concept_code": "thermodynamic-process-types",
        "front": "What is an isothermal process for an ideal gas, and what is ΔU?",
        "back": "Temperature constant; ΔU = 0, so Q = W.",
        "explanation": "For ideal gas, U depends only on T, so isothermal ⇒ no change in U.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-06",
        "concept_code": "thermodynamic-process-types",
        "front": "In an adiabatic process for an ideal gas, what is Q and how are P, V related?",
        "back": "Q = 0; PV^γ = constant (γ = C_P/C_V).",
        "explanation": "Also TV^{γ−1} = constant and T^γ P^{1−γ} = constant.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-07",
        "concept_code": "second-law-and-carnot",
        "front": "State Kelvin–Planck form of the second law (idea).",
        "back": "No engine can convert heat completely into work in a cyclic process without rejecting heat to a sink.",
        "explanation": "A 100% efficient heat engine in a cycle is impossible.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    {
        "card_key": "phy-thermo-08",
        "concept_code": "second-law-and-carnot",
        "front": "Efficiency of a Carnot engine operating between T_H and T_C (kelvin)?",
        "back": "η = 1 − T_C/T_H",
        "explanation": "Carnot efficiency is the maximum possible between two given temperatures.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Thermodynamics",
        "class_level": "11",
    },
    # ── Kinetic Theory (Class 11) ─────────────────────────────────────────
    {
        "card_key": "phy-kt-01",
        "concept_code": "behaviour-of-gases",
        "front": "Write the ideal gas equation.",
        "back": "PV = nRT (or PV = Nk_B T).",
        "explanation": "R is the universal gas constant; k_B is Boltzmann’s constant.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-02",
        "concept_code": "behaviour-of-gases",
        "front": "What is absolute zero on the Celsius scale according to the ideal gas extrapolation?",
        "back": "−273.15 °C (0 K).",
        "explanation": "Volume (or pressure) of an ideal gas extrapolates to zero at absolute zero.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-03",
        "concept_code": "kinetic-interpretation-temperature",
        "front": "Relate absolute temperature T to average translational KE per molecule of an ideal gas.",
        "back": "(1/2) m ⟨v²⟩ = (3/2) k_B T",
        "explanation": "Temperature measures the average translational kinetic energy of molecules.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-04",
        "concept_code": "kinetic-interpretation-temperature",
        "front": "Pressure of an ideal gas in kinetic theory: P = ?",
        "back": "P = (1/3) ρ ⟨v²⟩ = (1/3) (Nm/V) ⟨v²⟩",
        "explanation": "Derived from momentum transfer in elastic collisions with the walls.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-05",
        "concept_code": "law-of-equipartition",
        "front": "State the law of equipartition of energy.",
        "back": "Each quadratic energy term (degree of freedom) contributes (1/2) k_B T per molecule on average.",
        "explanation": "For a monatomic gas, 3 translational degrees ⇒ U = (3/2) nRT.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-06",
        "concept_code": "law-of-equipartition",
        "front": "Why is γ = C_P/C_V = 5/3 for a monatomic ideal gas?",
        "back": "C_V = (3/2)R, C_P = C_V + R = (5/2)R ⇒ γ = 5/3.",
        "explanation": "Three translational degrees of freedom only for monatomic gases.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-07",
        "concept_code": "mean-free-path",
        "front": "Define mean free path.",
        "back": "Average distance a molecule travels between successive collisions.",
        "explanation": "It increases with decreasing density (fewer collisions).",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    {
        "card_key": "phy-kt-08",
        "concept_code": "mean-free-path",
        "front": "Approximate expression for mean free path λ in terms of number density n and molecular diameter d?",
        "back": "λ ≈ 1/(√2 π d² n)",
        "explanation": "NCERT gives this standard kinetic-theory estimate.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 11 Physics — Kinetic Theory",
        "class_level": "11",
    },
    # ── Electrostatics (Class 12) ─────────────────────────────────────────
    {
        "card_key": "phy-es-01",
        "concept_code": "coulomb-force",
        "front": "State Coulomb’s law for two point charges in vacuum.",
        "back": "F = (1/(4πε₀)) (q₁q₂/r²), along the line joining charges (attractive if opposite signs).",
        "explanation": "Force is equal and opposite on the two charges (Newton’s third law).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electric Charges and Fields / Electrostatics",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-02",
        "concept_code": "coulomb-force",
        "front": "How does Coulomb force change if distance doubles and both charges are doubled?",
        "back": "Force remains the same: (2q)(2q)/(2r)² = q²/r².",
        "explanation": "Numerator ×4, denominator ×4 cancel.",
        "difficulty": "easy",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electric Charges and Fields / Electrostatics",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-03",
        "concept_code": "field-potential-relation",
        "front": "Relate electric field E and potential V in one dimension.",
        "back": "E = −dV/dx (field points from high to low potential).",
        "explanation": "In general, E = −∇V.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electrostatic Potential and Capacitance",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-04",
        "concept_code": "field-potential-relation",
        "front": "Potential due to a point charge q at distance r in vacuum?",
        "back": "V = (1/(4πε₀)) (q/r), taking V(∞) = 0.",
        "explanation": "Potential is a scalar; field is the negative gradient of V.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electrostatic Potential and Capacitance",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-05",
        "concept_code": "field-potential-relation",
        "front": "Work done by electrostatic field in moving a charge between two points depends on path?",
        "back": "No — electrostatic field is conservative; work depends only on potential difference.",
        "explanation": "W_ext (quasi-static) = q(V_f − V_i) when kinetic energy is unchanged.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electrostatic Potential and Capacitance",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-06",
        "concept_code": "parallel-plate-capacitor",
        "front": "Capacitance of a parallel-plate capacitor (area A, separation d, vacuum)?",
        "back": "C = ε₀ A/d",
        "explanation": "Inserting a dielectric of constant K multiplies C by K.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electrostatic Potential and Capacitance",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-07",
        "concept_code": "parallel-plate-capacitor",
        "front": "Energy stored in a capacitor with charge Q and capacitance C?",
        "back": "U = Q²/(2C) = ½CV² = ½QV",
        "explanation": "Energy resides in the electric field between the plates.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electrostatic Potential and Capacitance",
        "class_level": "12",
    },
    {
        "card_key": "phy-es-08",
        "concept_code": "parallel-plate-capacitor",
        "front": "If plate separation of an isolated charged parallel-plate capacitor is increased, what happens to V and U?",
        "back": "C decreases; with Q fixed, V = Q/C and U = Q²/(2C) both increase.",
        "explanation": "Work is done in separating plates against attraction, increasing stored energy.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Electrostatic Potential and Capacitance",
        "class_level": "12",
    },
    # ── Current Electricity (Class 12) ────────────────────────────────────
    {
        "card_key": "phy-ce-01",
        "concept_code": "ohms-law-concept",
        "front": "State Ohm’s law.",
        "back": "V = IR for many conductors at constant temperature (I ∝ V).",
        "explanation": "Materials obeying this linear relation are ohmic.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-02",
        "concept_code": "ohms-law-concept",
        "front": "Define electrical resistance and its SI unit.",
        "back": "R = V/I; unit ohm (Ω).",
        "explanation": "Resistance opposes current; conductance G = 1/R.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-03",
        "concept_code": "drift-velocity",
        "front": "Define drift velocity of free electrons in a conductor.",
        "back": "Average velocity of electrons under an applied electric field (superposed on random thermal motion).",
        "explanation": "Current I = n e A v_d.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-04",
        "concept_code": "drift-velocity",
        "front": "How is drift speed related to current density j and number density n?",
        "back": "j = n e v_d (magnitudes for electrons).",
        "explanation": "v_d is typically ~10⁻⁴ m/s — much smaller than thermal speeds.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-05",
        "concept_code": "factors-affecting-resistance",
        "front": "How does resistance of a wire depend on length L and cross-section A?",
        "back": "R = ρ L/A (ρ = resistivity).",
        "explanation": "Longer or thinner wires have higher resistance for the same material.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-06",
        "concept_code": "factors-affecting-resistance",
        "front": "How does resistivity of a metal typically vary with temperature?",
        "back": "Increases approximately linearly: ρ_T = ρ₀[1 + α(T − T₀)].",
        "explanation": "α is the temperature coefficient of resistivity.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-07",
        "concept_code": "kcl-kvl",
        "front": "State Kirchhoff’s current law (KCL).",
        "back": "Algebraic sum of currents at a junction is zero (charge conservation).",
        "explanation": "Currents into the junction equal currents leaving it.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    {
        "card_key": "phy-ce-08",
        "concept_code": "kcl-kvl",
        "front": "State Kirchhoff’s voltage law (KVL).",
        "back": "Algebraic sum of potential differences around any closed loop is zero.",
        "explanation": "Follows from the conservative nature of electrostatic forces in steady circuits.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Current Electricity",
        "class_level": "12",
    },
    # ── Optics (Class 12) ─────────────────────────────────────────────────
    {
        "card_key": "phy-opt-01",
        "concept_code": "principal-focus-spherical-mirror",
        "front": "Define the principal focus of a concave spherical mirror.",
        "back": "Point on the principal axis where rays parallel to the axis converge after reflection.",
        "explanation": "For a convex mirror, the focus is virtual (rays appear to diverge from F).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-02",
        "concept_code": "principal-focus-spherical-mirror",
        "front": "Relation between focal length f and radius of curvature R for a spherical mirror (paraxial)?",
        "back": "f = R/2",
        "explanation": "Valid in the paraxial (small-angle) approximation.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-03",
        "concept_code": "mirror-formula",
        "front": "Write the mirror formula (Cartesian sign convention as in NCERT).",
        "back": "1/v + 1/u = 1/f",
        "explanation": "u, v, f are signed according to the NCERT Cartesian convention.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-04",
        "concept_code": "mirror-formula",
        "front": "Lateral magnification of a spherical mirror?",
        "back": "m = h′/h = −v/u",
        "explanation": "Negative m means inverted image (real for concave, typical cases).",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-05",
        "concept_code": "refractive-index",
        "front": "Define absolute refractive index of a medium.",
        "back": "n = c/v, where c is speed of light in vacuum and v in the medium.",
        "explanation": "Relative refractive index n₂₁ = n₂/n₁ = v₁/v₂.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-06",
        "concept_code": "refractive-index",
        "front": "State Snell’s law for refraction at a plane interface.",
        "back": "n₁ sin i = n₂ sin r",
        "explanation": "Also written μ = sin i / sin r for air-to-medium when μ is absolute RI of the medium.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-07",
        "concept_code": "lens-formula",
        "front": "Write the thin-lens formula (NCERT sign convention).",
        "back": "1/v − 1/u = 1/f",
        "explanation": "Note the sign difference from the mirror formula.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-08",
        "concept_code": "lens-power-focal-length",
        "front": "Define power of a lens and its unit.",
        "back": "P = 1/f (f in metres); unit dioptre (D).",
        "explanation": "Convex (converging) lenses have positive power in the usual convention.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-09",
        "concept_code": "lens-power-focal-length",
        "front": "Two thin lenses in contact have powers P₁ and P₂. Net power?",
        "back": "P = P₁ + P₂",
        "explanation": "Equivalent focal length satisfies 1/F = 1/f₁ + 1/f₂ for thin lenses in contact.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Ray Optics and Optical Instruments",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-10",
        "concept_code": "interference-young",
        "front": "In Young’s double-slit experiment, fringe width β for wavelength λ, slit separation d, screen distance D?",
        "back": "β = λD/d",
        "explanation": "Bright fringes at path difference mλ; dark at (2m−1)λ/2.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Wave Optics",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-11",
        "concept_code": "interference-young",
        "front": "Condition for constructive interference (bright fringe) in YDSE for path difference Δx?",
        "back": "Δx = mλ (m = 0, ±1, ±2, …)",
        "explanation": "Destructive: Δx = (2m−1)λ/2.",
        "difficulty": "hard",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Wave Optics",
        "class_level": "12",
    },
    {
        "card_key": "phy-opt-12",
        "concept_code": "interference-young",
        "front": "If YDSE is immersed in water (n > 1), what happens to fringe width (other things fixed)?",
        "back": "β decreases because effective wavelength λ/n decreases: β′ = (λ/n)D/d.",
        "explanation": "Wavelength in the medium is λ/n; slit geometry and D unchanged.",
        "difficulty": "medium",
        "source": "NCERT",
        "source_reference": "NCERT Class 12 Physics — Wave Optics",
        "class_level": "12",
    },
]
