"""Human-authored NCERT-curriculum-aligned DRAFT catalog for Batch A.

Provenance truthfulness:
- origin: human-authored (not scraped official papers)
- alignment: NCERT UG curriculum concepts (not verbatim NCERT text)
- NOT official NTA / official NEET paper items

SME review remains mandatory before publish.
"""

from __future__ import annotations

from typing import Any

BATCH_ID = "acquisition-batch-A-diversify-p0"
MODEL_USED = "human-authored-batch-a"
PROMPT_VERSION = "batch-a-v1"


def _q(
    *,
    source_key: str,
    chapter_key: str,
    concept_code: str,
    title: str,
    stem: str,
    options: tuple[str, str, str, str],
    correct: str,
    explanation: str,
    difficulty: str,
) -> dict[str, Any]:
    labels = ("A", "B", "C", "D")
    return {
        "source_key": source_key,
        "chapter_key": chapter_key,
        "concept_code": concept_code,
        "title": title,
        "stem": stem,
        "options": [{"label": labels[i], "text": options[i]} for i in range(4)],
        "correct_option": correct,
        "explanation": explanation,
        "difficulty": difficulty,
    }


# ~74 items: Physics 20, Chemistry 20, Botany 10, Zoology 24
BATCH_A_QUESTIONS: list[dict[str, Any]] = [
    # ---- Physics · Electrostatics (10) ----
    _q(
        source_key="batch-a-phy-es-01",
        chapter_key="electrostatics",
        concept_code="coulomb-force",
        title="Coulomb force direction",
        stem="Two like point charges placed in vacuum will:",
        options=(
            "Attract each other",
            "Repel each other",
            "Experience no force",
            "Orbit each other without force",
        ),
        correct="B",
        explanation="Like charges repel; unlike charges attract, as described by Coulomb's law.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-es-02",
        chapter_key="electrostatics",
        concept_code="coulomb-force",
        title="Coulomb force distance dependence",
        stem="If the separation between two point charges is doubled, the Coulomb force becomes:",
        options=("2 times", "4 times", "1/2", "1/4"),
        correct="D",
        explanation="F ∝ 1/r², so doubling r reduces force to one-fourth.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-es-03",
        chapter_key="electrostatics",
        concept_code="coulomb-force",
        title="SI unit of charge",
        stem="The SI unit of electric charge is the:",
        options=("Volt", "Ampere", "Coulomb", "Ohm"),
        correct="C",
        explanation="Electric charge is measured in coulomb (C) in SI.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-es-04",
        chapter_key="electrostatics",
        concept_code="field-potential-relation",
        title="Electric field unit",
        stem="Electric field intensity has SI unit:",
        options=("N/C or V/m", "N·m", "C/N", "J·s"),
        correct="A",
        explanation="E = F/q gives N/C; also E = −dV/dx gives V/m.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-es-05",
        chapter_key="electrostatics",
        concept_code="field-potential-relation",
        title="Field inside conductor",
        stem="In electrostatic equilibrium, the electric field inside a charged conductor is:",
        options=("Maximum at centre", "Uniform and non-zero", "Zero", "Infinite"),
        correct="C",
        explanation="Free charges rearrange until the net field inside the conductor is zero.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-es-06",
        chapter_key="electrostatics",
        concept_code="field-potential-relation",
        title="Equipotential surface",
        stem="Work done in moving a charge on an equipotential surface is:",
        options=("Maximum", "Zero", "Equal to qV", "Infinite"),
        correct="B",
        explanation="Potential difference is zero on an equipotential surface, so W = qΔV = 0.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-es-07",
        chapter_key="electrostatics",
        concept_code="parallel-plate-capacitor",
        title="Capacitance formula",
        stem="Capacitance of a parallel plate capacitor (vacuum) is proportional to:",
        options=("d/A", "A/d", "A·d", "1/(A·d)"),
        correct="B",
        explanation="C = ε₀A/d for a vacuum parallel plate capacitor.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-es-08",
        chapter_key="electrostatics",
        concept_code="parallel-plate-capacitor",
        title="Dielectric effect",
        stem="Inserting a dielectric of dielectric constant K > 1 between capacitor plates (battery disconnected) generally:",
        options=(
            "Decreases capacitance",
            "Increases capacitance",
            "Leaves capacitance unchanged",
            "Makes capacitance infinite",
        ),
        correct="B",
        explanation="With dielectric, C = Kε₀A/d increases for K > 1.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-es-09",
        chapter_key="electrostatics",
        concept_code="parallel-plate-capacitor",
        title="Energy stored",
        stem="Energy stored in a capacitor charged to voltage V is:",
        options=("CV", "½CV²", "C²V", "2CV²"),
        correct="B",
        explanation="U = ½CV² = Q²/(2C) = ½QV.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-phy-es-10",
        chapter_key="electrostatics",
        concept_code="field-potential-relation",
        title="Potential due to point charge",
        stem="Electric potential due to a point charge varies with distance r as:",
        options=("1/r²", "1/r", "r", "r²"),
        correct="B",
        explanation="V = (1/(4πε₀))·q/r, so V ∝ 1/r.",
        difficulty="hard",
    ),
    # ---- Physics · Optics (10) ----
    _q(
        source_key="batch-a-phy-op-01",
        chapter_key="optics",
        concept_code="mirror-formula",
        title="Concave mirror focus",
        stem="Rays parallel to the principal axis of a concave mirror, after reflection, pass through:",
        options=("Centre of curvature", "Pole", "Focus", "Infinity only"),
        correct="C",
        explanation="By definition, paraxial parallel rays converge at the focal point after reflection.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-op-02",
        chapter_key="optics",
        concept_code="mirror-formula",
        title="Mirror formula relation",
        stem="The spherical mirror formula is:",
        options=("1/v − 1/u = 1/f", "1/v + 1/u = 1/f", "v + u = f", "vu = f"),
        correct="B",
        explanation="For spherical mirrors (Cartesian sign convention), 1/v + 1/u = 1/f.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-op-03",
        chapter_key="optics",
        concept_code="mirror-formula",
        title="Focal length and radius",
        stem="For a spherical mirror of small aperture, f is approximately:",
        options=("R", "R/2", "2R", "R/4"),
        correct="B",
        explanation="f ≈ R/2 for a spherical mirror.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-op-04",
        chapter_key="optics",
        concept_code="lens-formula",
        title="Convex lens power",
        stem="A converging thin lens in air has:",
        options=("Negative focal length", "Positive focal length", "Zero focal length", "Infinite power only"),
        correct="B",
        explanation="In the usual sign convention for lenses in air, a converging lens has positive f.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-op-05",
        chapter_key="optics",
        concept_code="lens-formula",
        title="Lens maker idea",
        stem="Power of a lens (in dioptre) equals:",
        options=("f (in m)", "1/f with f in metres", "f in cm", "1/f with f in cm only"),
        correct="B",
        explanation="P (D) = 1/f where f is in metres.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-op-06",
        chapter_key="optics",
        concept_code="lens-formula",
        title="Refractive index",
        stem="Absolute refractive index of a medium is:",
        options=(
            "Speed of light in medium / speed in vacuum",
            "Speed of light in vacuum / speed in medium",
            "Always less than 1",
            "Equal to wavelength only",
        ),
        correct="B",
        explanation="n = c/v; denser media generally have n > 1.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-phy-op-07",
        chapter_key="optics",
        concept_code="interference-young",
        title="YDSE fringe width",
        stem="In Young's double-slit experiment, fringe width β is:",
        options=(
            "Proportional to slit separation / screen distance",
            "Proportional to wavelength × screen distance / slit separation",
            "Independent of wavelength",
            "Equal to slit separation alone",
        ),
        correct="B",
        explanation="β = λD/d where D is screen distance and d slit separation.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-op-08",
        chapter_key="optics",
        concept_code="interference-young",
        title="Path difference bright fringe",
        stem="For constructive interference (bright fringe) in YDSE, path difference is typically:",
        options=("Odd multiple of λ/2", "Integer multiple of λ", "Always λ/4", "Independent of λ"),
        correct="B",
        explanation="Bright fringes occur when path difference is an integer multiple of λ.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-phy-op-09",
        chapter_key="optics",
        concept_code="interference-young",
        title="Wavelength effect on fringes",
        stem="If wavelength used in YDSE increases, fringe width:",
        options=("Decreases", "Increases", "Remains same", "Becomes zero"),
        correct="B",
        explanation="β ∝ λ, so larger wavelength widens fringes.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-phy-op-10",
        chapter_key="optics",
        concept_code="lens-formula",
        title="Total internal reflection condition",
        stem="Total internal reflection can occur when light travels:",
        options=(
            "From rarer to denser medium at any angle",
            "From denser to rarer medium at incidence greater than critical angle",
            "Only in vacuum",
            "Only for sound waves",
        ),
        correct="B",
        explanation="TIR requires denser→rarer incidence with i > ic where sin ic = n₂/n₁.",
        difficulty="hard",
    ),
    # ---- Chemistry · Equilibrium (10) ----
    _q(
        source_key="batch-a-chem-eq-01",
        chapter_key="equilibrium",
        concept_code="equilibrium-constant",
        title="Dynamic equilibrium",
        stem="At chemical equilibrium:",
        options=(
            "Forward reaction stops",
            "Reverse reaction stops",
            "Forward and reverse rates are equal",
            "Concentrations become zero",
        ),
        correct="C",
        explanation="Equilibrium is dynamic: opposing rates are equal and concentrations remain constant.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-eq-02",
        chapter_key="equilibrium",
        concept_code="equilibrium-constant",
        title="Kc expression",
        stem="For aA + bB ⇌ cC + dD, Kc equals:",
        options=(
            "[A]^a[B]^b / [C]^c[D]^d",
            "[C]^c[D]^d / [A]^a[B]^b",
            "[A][B]/[C][D] without powers",
            "Always exactly 1",
        ),
        correct="B",
        explanation="Kc is products over reactants raised to stoichiometric powers.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-eq-03",
        chapter_key="equilibrium",
        concept_code="equilibrium-constant",
        title="Le Chatelier temperature",
        stem="For an exothermic equilibrium, increasing temperature generally:",
        options=(
            "Favours products",
            "Favours reactants",
            "Has no effect",
            "Always increases K indefinitely",
        ),
        correct="B",
        explanation="Heat acts like a product for exothermic reactions; raising T shifts left (reactants).",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-chem-eq-04",
        chapter_key="equilibrium",
        concept_code="ph-and-kw",
        title="Neutral water pH",
        stem="At 25°C, pure water has pH approximately:",
        options=("0", "7", "14", "1"),
        correct="B",
        explanation="At 25°C, [H+] = 10⁻⁷ M so pH = 7 for pure water.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-eq-05",
        chapter_key="equilibrium",
        concept_code="ph-and-kw",
        title="Kw value",
        stem="Ionic product of water Kw at 25°C is approximately:",
        options=("10⁻⁷", "10⁻¹⁴", "10⁻¹", "1"),
        correct="B",
        explanation="Kw = [H+][OH−] ≈ 1.0 × 10⁻¹⁴ at 25°C.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-chem-eq-06",
        chapter_key="equilibrium",
        concept_code="ph-and-kw",
        title="Acidic pH",
        stem="A solution with [H+] = 10⁻³ M has pH:",
        options=("3", "11", "7", "−3"),
        correct="A",
        explanation="pH = −log[H+] = 3.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-eq-07",
        chapter_key="equilibrium",
        concept_code="ksp-basics",
        title="Ksp meaning",
        stem="For AgCl(s) ⇌ Ag+(aq) + Cl−(aq), Ksp equals:",
        options=("[Ag+][Cl−]", "[AgCl]", "[Ag+]/[Cl−]", "[Ag+] + [Cl−]"),
        correct="A",
        explanation="For this 1:1 salt, Ksp = [Ag+][Cl−] in saturated solution.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-chem-eq-08",
        chapter_key="equilibrium",
        concept_code="ksp-basics",
        title="Common ion effect",
        stem="Adding NaCl to a saturated AgCl solution generally:",
        options=(
            "Increases AgCl solubility",
            "Decreases AgCl solubility",
            "Has no effect on solubility",
            "Converts AgCl to gas",
        ),
        correct="B",
        explanation="Common Cl− ion shifts equilibrium left, reducing AgCl solubility.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-chem-eq-09",
        chapter_key="equilibrium",
        concept_code="equilibrium-constant",
        title="Kp and Kc",
        stem="Kp and Kc are related by:",
        options=("Kp = Kc", "Kp = Kc(RT)^{Δn}", "Kp = Kc/RT", "Kp = Kc + RT"),
        correct="B",
        explanation="Kp = Kc(RT)^{Δn} where Δn is change in gaseous moles.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-chem-eq-10",
        chapter_key="equilibrium",
        concept_code="ph-and-kw",
        title="Buffer concept",
        stem="A buffer solution resists change in:",
        options=("Temperature only", "pH on addition of small acid/base", "Volume only", "Colour only"),
        correct="B",
        explanation="Buffers maintain relatively stable pH when small amounts of acid or base are added.",
        difficulty="medium",
    ),
    # ---- Chemistry · Organic basics (10) ----
    _q(
        source_key="batch-a-chem-org-01",
        chapter_key="organic-basics",
        concept_code="homologous-series",
        title="Homologous difference",
        stem="Consecutive members of a homologous series differ by:",
        options=("CH3", "CH2", "OH", "COOH"),
        correct="B",
        explanation="Homologues differ by a −CH2− unit.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-org-02",
        chapter_key="organic-basics",
        concept_code="homologous-series",
        title="Alkane general formula",
        stem="General formula of alkanes is:",
        options=("CnH2n", "CnH2n+2", "CnH2n−2", "CnHn"),
        correct="B",
        explanation="Saturated open-chain alkanes follow CnH2n+2.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-org-03",
        chapter_key="organic-basics",
        concept_code="inductive-mesomeric",
        title="Inductive effect",
        stem="The inductive effect involves:",
        options=(
            "Delocalisation of π electrons only",
            "σ-electron displacement along a chain",
            "Only hydrogen bonding",
            "Nuclear fusion",
        ),
        correct="B",
        explanation="Inductive effect is permanent σ-electron shift due to electronegativity differences.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-chem-org-04",
        chapter_key="organic-basics",
        concept_code="inductive-mesomeric",
        title="Resonance",
        stem="Resonance (mesomeric) effect is associated with:",
        options=(
            "Only σ bonds in alkanes",
            "Delocalisation of electrons in conjugated systems",
            "Ionic lattice energy only",
            "Nuclear spin only",
        ),
        correct="B",
        explanation="Resonance involves π-electron delocalisation in conjugated systems.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-chem-org-05",
        chapter_key="organic-basics",
        concept_code="structural-isomerism",
        title="Structural isomers",
        stem="Structural isomers have:",
        options=(
            "Same structure, different formula",
            "Same molecular formula, different connectivity",
            "Same connectivity, different formula",
            "Identical in all respects",
        ),
        correct="B",
        explanation="Structural isomers share molecular formula but differ in bonding arrangement.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-org-06",
        chapter_key="organic-basics",
        concept_code="structural-isomerism",
        title="Functional group isomerism example",
        stem="Ethanol and dimethyl ether are examples of:",
        options=("Chain isomers", "Functional group isomers", "Optical isomers only", "Geometrical isomers only"),
        correct="B",
        explanation="Same formula C2H6O but different functional groups (alcohol vs ether).",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-chem-org-07",
        chapter_key="organic-basics",
        concept_code="homologous-series",
        title="Functional group of carboxylic acid",
        stem="The functional group of carboxylic acids is:",
        options=("−CHO", "−COOH", "−OH only", "−NH2"),
        correct="B",
        explanation="Carboxylic acids contain the −COOH group.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-org-08",
        chapter_key="organic-basics",
        concept_code="inductive-mesomeric",
        title="Electron withdrawing group",
        stem="Which group is typically electron-withdrawing by inductive effect?",
        options=("−CH3", "−NO2", "−C2H5", "−CH2CH3 alkyl"),
        correct="B",
        explanation="−NO2 is strongly electron-withdrawing; alkyl groups are generally electron-releasing.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-chem-org-09",
        chapter_key="organic-basics",
        concept_code="structural-isomerism",
        title="Tetravalency of carbon",
        stem="Carbon is tetravalent because it has:",
        options=("2 valence electrons", "4 valence electrons", "6 valence electrons", "8 valence electrons"),
        correct="B",
        explanation="Carbon (atomic number 6) has four valence electrons and forms four covalent bonds.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-chem-org-10",
        chapter_key="organic-basics",
        concept_code="inductive-mesomeric",
        title="Carbocation stability trend",
        stem="Among simple alkyl carbocations, relative stability generally follows:",
        options=("1° > 2° > 3°", "3° > 2° > 1°", "1° = 2° = 3°", "Methyl > 3°"),
        correct="B",
        explanation="Tertiary carbocations are most stabilized by hyperconjugation/inductive effects.",
        difficulty="hard",
    ),
    # ---- Botany · Cell (10) ----
    _q(
        source_key="batch-a-bot-cell-01",
        chapter_key="cell",
        concept_code="prokaryote-eukaryote",
        title="Prokaryote nucleus",
        stem="Prokaryotic cells typically lack:",
        options=("Ribosomes", "Plasma membrane", "A membrane-bound nucleus", "DNA"),
        correct="C",
        explanation="Prokaryotes lack a true membrane-bound nucleus; genetic material is in nucleoid.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-bot-cell-02",
        chapter_key="cell",
        concept_code="prokaryote-eukaryote",
        title="Cell theory",
        stem="According to cell theory, new cells arise from:",
        options=("Spontaneous generation", "Pre-existing cells", "Only viruses", "Only abiotic crystals"),
        correct="B",
        explanation="Omnis cellula e cellula — cells arise from pre-existing cells.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-bot-cell-03",
        chapter_key="cell",
        concept_code="mitochondria-chloroplast",
        title="Mitochondria function",
        stem="Mitochondria are primarily sites of:",
        options=("Photosynthesis", "Aerobic respiration / ATP synthesis", "Protein glycosylation only", "DNA replication only in nucleus"),
        correct="B",
        explanation="Mitochondria house pathways of cellular respiration producing ATP.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-bot-cell-04",
        chapter_key="cell",
        concept_code="mitochondria-chloroplast",
        title="Chloroplast pigment",
        stem="The green pigment essential for photosynthesis in chloroplasts is:",
        options=("Haemoglobin", "Chlorophyll", "Melanin", "Rhodopsin"),
        correct="B",
        explanation="Chlorophyll captures light energy for photosynthesis.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-bot-cell-05",
        chapter_key="cell",
        concept_code="mitochondria-chloroplast",
        title="Endosymbiotic clue",
        stem="Mitochondria and chloroplasts both have:",
        options=("Only one membrane", "Their own circular DNA", "No ribosomes", "Cell walls of peptidoglycan always"),
        correct="B",
        explanation="Both contain their own circular DNA, supporting endosymbiotic origin.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-bot-cell-06",
        chapter_key="cell",
        concept_code="fluid-mosaic",
        title="Fluid mosaic model",
        stem="The fluid mosaic model describes the plasma membrane as:",
        options=(
            "A rigid protein sheet only",
            "A fluid lipid bilayer with embedded proteins",
            "A cellulose wall",
            "A nuclear envelope only",
        ),
        correct="B",
        explanation="Singer–Nicolson model: fluid phospholipid bilayer with mosaic of proteins.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-bot-cell-07",
        chapter_key="cell",
        concept_code="fluid-mosaic",
        title="Selective permeability",
        stem="The plasma membrane is selectively permeable, meaning it:",
        options=(
            "Allows all substances freely",
            "Allows some substances more readily than others",
            "Blocks all ions always",
            "Is impermeable to water always",
        ),
        correct="B",
        explanation="Selective permeability regulates entry/exit of substances.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-bot-cell-08",
        chapter_key="cell",
        concept_code="prokaryote-eukaryote",
        title="Plant cell wall",
        stem="Plant cell walls are mainly composed of:",
        options=("Peptidoglycan", "Cellulose", "Chitin only", "Keratin"),
        correct="B",
        explanation="Plant cell walls are primarily cellulose-based.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-bot-cell-09",
        chapter_key="cell",
        concept_code="fluid-mosaic",
        title="Ribosome site",
        stem="Protein synthesis occurs on:",
        options=("Lysosomes", "Ribosomes", "Vacuoles only", "Centrioles only"),
        correct="B",
        explanation="Ribosomes are the cellular sites of translation/protein synthesis.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-bot-cell-10",
        chapter_key="cell",
        concept_code="mitochondria-chloroplast",
        title="Golgi function",
        stem="The Golgi apparatus is mainly involved in:",
        options=(
            "ATP synthesis",
            "Packaging and modification of proteins/lipids",
            "Photosynthesis light reaction",
            "DNA replication exclusively",
        ),
        correct="B",
        explanation="Golgi modifies, sorts, and packages macromolecules for secretion or delivery.",
        difficulty="hard",
    ),
    # ---- Zoology · Animal Kingdom (8) ----
    _q(
        source_key="batch-a-zoo-ak-01",
        chapter_key="animal-kingdom",
        concept_code="levels-of-organisation",
        title="Tissue grade",
        stem="Animals with tissue-level organisation include:",
        options=("Protozoa only", "Cnidarians (e.g., Hydra)", "All sponges only", "Viruses"),
        correct="B",
        explanation="Cnidarians show tissue grade; sponges are cellular grade.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-ak-02",
        chapter_key="animal-kingdom",
        concept_code="levels-of-organisation",
        title="Radial symmetry",
        stem="Radial symmetry is characteristic of:",
        options=("Annelids", "Cnidarians", "Arthropods only", "Mammals only"),
        correct="B",
        explanation="Cnidarians typically exhibit radial symmetry.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-ak-03",
        chapter_key="animal-kingdom",
        concept_code="porifera-cnidaria",
        title="Porifera feature",
        stem="Canal system for water circulation is a hallmark of:",
        options=("Porifera", "Annelida", "Mollusca only", "Echinodermata larvae only"),
        correct="A",
        explanation="Sponges (Porifera) possess a characteristic canal system.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-ak-04",
        chapter_key="animal-kingdom",
        concept_code="porifera-cnidaria",
        title="Cnidocytes",
        stem="Cnidocytes (stinging cells) are found in:",
        options=("Porifera", "Cnidaria", "Platyhelminthes only", "Nematodes only"),
        correct="B",
        explanation="Cnidocytes are diagnostic of Cnidaria.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-ak-05",
        chapter_key="animal-kingdom",
        concept_code="chordate-features",
        title="Notochord",
        stem="A defining chordate feature at some stage of life is the:",
        options=("Ventral solid nerve cord only", "Notochord", "Exoskeleton of chitin only", "Absence of pharyngeal slits always"),
        correct="B",
        explanation="Chordates possess a notochord (at least in embryonic stages).",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-ak-06",
        chapter_key="animal-kingdom",
        concept_code="chordate-features",
        title="Nerve cord in chordates",
        stem="The nerve cord in chordates is typically:",
        options=("Ventral and solid", "Dorsal and hollow", "Absent", "Lateral and segmented only in insects"),
        correct="B",
        explanation="Chordates have a dorsal hollow nerve cord.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-ak-07",
        chapter_key="animal-kingdom",
        concept_code="levels-of-organisation",
        title="Coelom",
        stem="Animals with a true coelom lined by mesoderm are called:",
        options=("Acoelomates", "Pseudocoelomates", "Coelomates", "Asymmetrical only"),
        correct="C",
        explanation="Coelomates have a body cavity lined by mesoderm.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-zoo-ak-08",
        chapter_key="animal-kingdom",
        concept_code="chordate-features",
        title="Post-anal tail",
        stem="Presence of a post-anal tail at some life stage is a feature of:",
        options=("Only arthropods", "Chordates", "Only sponges", "Only fungi"),
        correct="B",
        explanation="A post-anal tail is one of the fundamental chordate characters.",
        difficulty="hard",
    ),
    # ---- Zoology · Biomolecules (8) ----
    _q(
        source_key="batch-a-zoo-bm-01",
        chapter_key="biomolecules",
        concept_code="enzyme-basics",
        title="Enzyme nature",
        stem="Most enzymes are chemically:",
        options=("Lipids", "Proteins", "Simple sugars only", "Inorganic salts only"),
        correct="B",
        explanation="Enzymes are predominantly proteins (some RNA catalysts exist, but NEET focus is proteins).",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-bm-02",
        chapter_key="biomolecules",
        concept_code="enzyme-basics",
        title="Enzyme and temperature",
        stem="Beyond an optimum temperature, enzyme activity usually:",
        options=("Increases forever", "Decreases due to denaturation", "Is unaffected", "Converts enzyme to DNA"),
        correct="B",
        explanation="High temperature denatures protein structure, reducing activity.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-bm-03",
        chapter_key="biomolecules",
        concept_code="biomolecule-classes",
        title="Carbohydrate monomer",
        stem="The monomer unit of proteins is:",
        options=("Glucose", "Amino acid", "Nucleotide", "Fatty acid"),
        correct="B",
        explanation="Proteins are polymers of amino acids.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-bm-04",
        chapter_key="biomolecules",
        concept_code="biomolecule-classes",
        title="Glycogen",
        stem="Glycogen is a storage polysaccharide in:",
        options=("Plant cell walls", "Animals", "Only bacteria capsules", "Only nucleic acids"),
        correct="B",
        explanation="Glycogen is the animal storage carbohydrate; starch is typical in plants.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-bm-05",
        chapter_key="biomolecules",
        concept_code="dna-rna",
        title="DNA sugar",
        stem="The sugar in DNA is:",
        options=("Ribose", "Deoxyribose", "Glucose", "Fructose"),
        correct="B",
        explanation="DNA contains 2-deoxyribose; RNA contains ribose.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-bm-06",
        chapter_key="biomolecules",
        concept_code="dna-rna",
        title="Base pairing",
        stem="In DNA, adenine pairs with:",
        options=("Guanine", "Cytosine", "Thymine", "Uracil"),
        correct="C",
        explanation="A pairs with T (two hydrogen bonds) in DNA.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-bm-07",
        chapter_key="biomolecules",
        concept_code="dna-rna",
        title="RNA base",
        stem="Uracil is a nitrogenous base found in:",
        options=("DNA only", "RNA", "Both DNA and proteins", "Only ATP sugar"),
        correct="B",
        explanation="RNA uses uracil instead of thymine.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-bm-08",
        chapter_key="biomolecules",
        concept_code="enzyme-basics",
        title="Competitive inhibition idea",
        stem="A competitive inhibitor typically:",
        options=(
            "Binds to an allosteric site only",
            "Competes with substrate for the active site",
            "Destroys the enzyme permanently always",
            "Increases Vmax without affecting Km",
        ),
        correct="B",
        explanation="Competitive inhibitors resemble substrate and compete for the active site.",
        difficulty="hard",
    ),
    # ---- Zoology · Human Reproduction (8) ----
    _q(
        source_key="batch-a-zoo-hr-01",
        chapter_key="human-reproduction",
        concept_code="gonads-ducts",
        title="Male gonad",
        stem="The primary male sex organ producing sperms is the:",
        options=("Prostate", "Testis", "Seminal vesicle", "Epididymis only as gonad"),
        correct="B",
        explanation="Testes are the male gonads producing spermatozoa and testosterone.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-hr-02",
        chapter_key="human-reproduction",
        concept_code="gonads-ducts",
        title="Female gonad",
        stem="The primary female sex organ producing ova is the:",
        options=("Uterus", "Ovary", "Fallopian tube", "Cervix"),
        correct="B",
        explanation="Ovaries produce ova and hormones such as estrogen and progesterone.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-hr-03",
        chapter_key="human-reproduction",
        concept_code="spermatogenesis-oogenesis",
        title="Spermatogenesis site",
        stem="Spermatogenesis occurs in the:",
        options=("Seminiferous tubules", "Prostate gland", "Bulbourethral gland only", "Uterus"),
        correct="A",
        explanation="Sperm formation occurs in seminiferous tubules of the testis.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-hr-04",
        chapter_key="human-reproduction",
        concept_code="spermatogenesis-oogenesis",
        title="Polar bodies",
        stem="Polar bodies are formed during:",
        options=("Spermatogenesis only", "Oogenesis", "Fertilization only in males", "Implantation only"),
        correct="B",
        explanation="Oogenesis produces polar bodies to conserve cytoplasm in the ovum.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-hr-05",
        chapter_key="human-reproduction",
        concept_code="menstrual-phases",
        title="Ovulation hormone surge",
        stem="Ovulation in a typical cycle is triggered mainly by a surge of:",
        options=("FSH only without LH", "LH", "Prolactin only", "Oxytocin only"),
        correct="B",
        explanation="LH surge mid-cycle triggers ovulation.",
        difficulty="medium",
    ),
    _q(
        source_key="batch-a-zoo-hr-06",
        chapter_key="human-reproduction",
        concept_code="menstrual-phases",
        title="Corpus luteum hormone",
        stem="The corpus luteum primarily secretes:",
        options=("FSH", "Progesterone", "TSH", "ADH"),
        correct="B",
        explanation="Corpus luteum secretes progesterone (and some estrogen) to maintain early pregnancy readiness.",
        difficulty="easy",
    ),
    _q(
        source_key="batch-a-zoo-hr-07",
        chapter_key="human-reproduction",
        concept_code="menstrual-phases",
        title="Fertilization site",
        stem="Fertilization in humans usually occurs in the:",
        options=("Ovary", "Ampulla of fallopian tube", "Vagina", "Uterine endometrium exclusively"),
        correct="B",
        explanation="Fertilization typically occurs in the ampullary region of the oviduct.",
        difficulty="hard",
    ),
    _q(
        source_key="batch-a-zoo-hr-08",
        chapter_key="human-reproduction",
        concept_code="gonads-ducts",
        title="Implantation",
        stem="Implantation of the blastocyst occurs in the:",
        options=("Ovary", "Endometrium of uterus", "Cervix only permanently", "Testis"),
        correct="B",
        explanation="The blastocyst implants in the uterine endometrium.",
        difficulty="hard",
    ),
]


def catalog_stats() -> dict[str, Any]:
    by_chapter: dict[str, int] = {}
    by_diff: dict[str, int] = {}
    for q in BATCH_A_QUESTIONS:
        by_chapter[q["chapter_key"]] = by_chapter.get(q["chapter_key"], 0) + 1
        by_diff[q["difficulty"]] = by_diff.get(q["difficulty"], 0) + 1
    return {
        "batch_id": BATCH_ID,
        "total": len(BATCH_A_QUESTIONS),
        "by_chapter_key": by_chapter,
        "by_difficulty": by_diff,
        "chapters": len(by_chapter),
    }
